### ISSUE TITLE
Working Offline

### ISSUE THREAD

**Issue by hajsf** [go-echarts/go-echarts#109]
I noticed that the generated html file is have the below 2 lines:

```html5
    <script src="https://go-echarts.github.io/go-echarts-assets/assets/echarts.min.js"></script>
    <link href="https://go-echarts.github.io/go-echarts-assets/assets/bulma.min.css" rel="stylesheet">
```
So, if I'm working offline, without internet connection, my file will not work properly, is there a way to work it off line, so I download these 2 files, and ask my output file to read the offline copy instead of the online one?

I noticed it is managed at the [header](https://github.com/go-echarts/go-echarts/blob/3b902f83a9e777a219d6e47308d0d8d2516e162f/templates/header.go) and at [base](https://github.com/go-echarts/go-echarts/blob/aeae62dcf8c194b1a6a27199922ab4887b991d86/charts/base.go`)

```html
package templates

var HeaderTpl = `
{{ define "header" }}
<head>
    <meta charset="utf-8">
    <title>{{ .PageTitle }}</title>
{{- range .JSAssets.Values }}
    <script src="{{ . }}"></script>
{{- end }}
{{- range .CSSAssets.Values }}
    <link href="{{ . }}" rel="stylesheet">
{{- end }}
</head>
{{ end }}
`
```
and
```go
// InitOpts contains options for the canvas.
type InitOpts struct {

	// 静态资源 host 地址
	AssetsHost string `default:"https://go-echarts.github.io/go-echarts-assets/assets/"`

}
```

**Comment by Koooooo-7** [comment]
yup, you can define the local path.f.e
```go
bar.SetGlobalOptions(
		charts.InitOpts{
			AssetsHost: "/home/example/src/",
		},
	)
```
```html
<script src="/home/example/src/echarts.min.js"></script>
<link href="/home/example/src/bulma.min.css" rel="stylesheet">
```

**Comment by hajsf** [comment]
Thanks, do I need to do this for every single chart? Is there a way to define it globally for ALL the chart elements to be created?

**Comment by electronjoe** [comment]
Thank you @hasanAjsf for the code snippet example for static hosting of the assets!

**Comment by electronjoe** [comment]
A brief update regarding Offline use (which I now have working in ~latest master).

If you are using `components.Page` to display multiple graphs, this over-writes the sub-graph's `AssetsHost`.

I achieved success with the following:

```golang
func httpserver(w http.ResponseWriter, req *http.Request) {
	// create a new line instance
	pmStd := charts.NewLine()
	// Add data...

	page := components.NewPage()
	page.Initialization.AssetsHost = "/static/"
	page.AddCharts(pmStd)
	page.Render(w)
}

func main() {
	fs := http.FileServer(http.Dir("./static"))
	http.Handle("/static/", http.StripPrefix("/static/", fs))
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8081", nil)
}
```
