### ISSUE TITLE
Replacing Bulma css

### ISSUE THREAD

**Issue by hajsf** [go-echarts/go-echarts#113]
Can I replace bulma css by semantic css?

**Comment by chenjiandongx** [comment]
@hajsf go-echarts v1 is no longer maintained so please try the new version v2, and bulma.css have been removed at v2 :)

**Comment by hajsf** [comment]
Did not get how to install it, I tried `go get github.com/go-echarts/go-echarts/v2`  but got error"
```
PS C:\Users\hasan.yousef> go get github.com/go-echarts/go-echarts/v2
cannot find package "github.com/go-echarts/go-echarts/v2" in any of:
        c:\go\src\github.com\go-echarts\go-echarts\v2 (from $GOROOT)
        C:\Users\hasan.yousef\go\src\github.com\go-echarts\go-echarts\v2 (from $GOPATH)
```

**Comment by chenjiandongx** [comment]
You cannot use v2 version as usual because of the gomod version management system. v2 is a new larget version which is not compatible with v1, so could you try to use gomod style to get go-echarts?

```
require "github.com/go-echarts/go-echarts/v2"
```

otherwise, you should clone the go-echarts project and move the codebase to the `v2 directory`...., it sounds stupid, but I can find out other workarounds....

**Comment by hajsf** [comment]
I moved the lib to v2 folder, and run the code, and looks still using `bulma` unless if I did something wrong

![image](https://user-images.githubusercontent.com/46838626/97261750-8ee80800-1830-11eb-8c57-2d0f390d3881.png)

![image](https://user-images.githubusercontent.com/46838626/97261836-bccd4c80-1830-11eb-83da-54d6e7f9751a.png)

**Comment by thenick775** [comment]
I saw the same thing until I switched to v2.0.1

`require github.com/go-echarts/go-echarts/v2 v2.0.1`

Now it only imports these two for me
<img width="658" alt="Screen Shot 2020-10-28 at 8 19 14 PM" src="https://user-images.githubusercontent.com/40526638/97521545-00bc7080-195b-11eb-8e80-4a4a5a23f1fe.png">

**Comment by chenjiandongx** [comment]
@hajsf try to switch to v2.0.1?
