### ISSUE TITLE
demo这么少，这让新手怎么用？？？？？你的良心不会痛吗？？？？

### ISSUE THREAD

**Issue by skkep** [go-echarts/go-echarts#115]
实例这么少，一看就是故意不想让大家用，故意提高门槛。。。。还有这么多star，简直是不能忍，作品不垃圾，作者良心tm垃圾！！！！！！！！

**Comment by chenjiandongx** [comment]
@skkep 👍 

https://github.com/go-echarts/examples 这里的示例是觉得太少吗？我的良心倒觉得蛮舒服的耶！
