### ISSUE TITLE
numbers format comma and point

### ISSUE THREAD

**Issue by diekloope** [go-echarts/go-echarts#119]
The numbers are presented in english format. Is it possible to format the numbers? For example in a german format = 1.000,20

**Comment by chenjiandongx** [comment]
A workaround of this case is setting the customized formatted

for example
```golang
// you can provide your js formatter like this
var myformatter = `function (params) {
		return params.name + ' : ' + params.value[2];
}`

// enable it by WithTooltipOpts
charts.WithTooltipOpts(opts.Tooltip{Show: true, Formatter: opts.FuncOpts(myformatter)}),
```

**Comment by diekloope** [comment]
Thanks a lot. Can I als format the values in the YAxis? I tried it with charts.WithYAxisOpts, but i was not successful.

**Comment by chenjiandongx** [comment]
here -> https://github.com/go-echarts/examples/blob/master/examples/bar.go#L134-L149

Don't forget to upgrade the go-echarts to v2.2.1

**Comment by diekloope** [comment]
Thanks. I can use the format function now.  👍
