### ISSUE TITLE
Creating a 3D scatter plot with custom colors for each data point

### ISSUE THREAD

**Issue by rishabh-bector** [go-echarts/go-echarts#123]
Hi, 

I can't figure out how to create a 3D scatter plot with a custom color for each point. In the scatter-3d example, the color is defined by the z coordinate of the point. Is there a way for me to customize this? For example, I'd like to make a 3D chart in which each point is color-coded based on a separate data as opposed to a component of the point's position.

Thank you!

**Comment by chenjiandongx** [comment]
Hi, @rishabh-bector 

The Chart3d-related module has been redesigned since the new version v2.1.0

now you could use the new API, for example

```golang
func scatter3DDataItem() *charts.Scatter3D {
	scatter3d := charts.NewScatter3D()
	scatter3d.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "user-defined item style"}),
		charts.WithXAxis3DOpts(opts.XAxis3D{Name: "MY-X-AXIS", Show: true}),
		charts.WithYAxis3DOpts(opts.YAxis3D{Name: "MY-Y-AXIS"}),
		charts.WithZAxis3DOpts(opts.ZAxis3D{Name: "MY-Z-AXIS"}),
	)

	scatter3d.AddSeries("scatter3d", []opts.Chart3DData{
		{Name: "point1", Value: []interface{}{10, 10, 10}, ItemStyle: &opts.ItemStyle{Color: "green"}},
		{Name: "point2", Value: []interface{}{15, 15, 15}, ItemStyle: &opts.ItemStyle{Color: "blue"}},
		{Name: "point3", Value: []interface{}{20, 20, 20}, ItemStyle: &opts.ItemStyle{Color: "red"}},
	})

	return scatter3d
}
```
Graph

![image](https://user-images.githubusercontent.com/19553554/98452878-5d573100-218e-11eb-8c97-91d3cd53edd6.png)
