### ISSUE TITLE
[Bug]SetSeriesOptions overwrites for multiple series in one graph

### ISSUE THREAD

**Issue by thenick775** [go-echarts/go-echarts#132]
**Describe the bug**
When using multiple series, I tried to color the lines using SetSeriesOptions for each series, but this resulted in both series having the same options.

using v2.2.1

**To Reproduce:**
Create an charts project from the line sample, and structure it as follows

```
        line := charts.NewLine()

	line.SetXAxis(getDates(d)).AddSeries("series1", getVals(d)).
		SetSeriesOptions(
			charts.WithLabelOpts(opts.Label{
				Show: false,
			}),
			charts.WithAreaStyleOpts(opts.AreaStyle{
				Color:   "#0465db",
				Opacity: 0.3,
			}),
			charts.WithLineChartOpts(opts.LineChart{
				Smooth: true,
			}),
			charts.WithLineStyleOpts(opts.LineStyle{
				Color: "#1cace6",
			}),
		)

	 line.AddSeries("series2", getVals(d2)).
		SetSeriesOptions(
			charts.WithLabelOpts(opts.Label{
				Show: false,
			}),
			charts.WithLineChartOpts(opts.LineChart{
				Smooth: true,
			}),
			charts.WithLineStyleOpts(opts.LineStyle{
				Color: "#2EFEF7",
			}),
		)
```

**Expected behavior**
Using SetSeriesOptions for each series should result in the lineStyle, areaStyle etc. being applied for each line independently in the resulting e-charts html

**Screenshots**
<img width="1157" alt="test" src="https://user-images.githubusercontent.com/40526638/99021221-0bf3cc80-2515-11eb-8e3d-e972edcab5f2.png">

Also wanted to say thanks again for writing this, as I found this project quite useful and easy to use

**Comment by geange** [comment]
For v2.2.1, maybe this is what you want. But I think your expected effect is a good idea, the function SetSeriesOptions() maybe named as SetGlobalSeriesOptions()? @chenjiandongx 

```
        line.SetXAxis(getDates(d)).AddSeries("series1", getVals(d),
		charts.WithLabelOpts(opts.Label{
			Show: false,
		}),
		charts.WithAreaStyleOpts(opts.AreaStyle{
			Color:   "#0465db",
			Opacity: 0.3,
		}),
		charts.WithLineChartOpts(opts.LineChart{
			Smooth: true,
		}),
		charts.WithLineStyleOpts(opts.LineStyle{
			Color: "#1cace6",
		}))

	line.AddSeries("series2", getVals(d2),
		charts.WithLabelOpts(opts.Label{
			Show: false,
		}),
		charts.WithLineChartOpts(opts.LineChart{
			Smooth: true,
		}),
		charts.WithLineStyleOpts(opts.LineStyle{
			Color: "#2EFEF7",
		}))
```

**Comment by chenjiandongx** [comment]
@thenick775  

The `SetSeriesOptions()` function does overwrite them every time and I will perfect the documentation later.

`SetGlobalSeriesOptions` will make developers confused as there is a `SetGlobalOptions` already. @geange

**Comment by chenjiandongx** [comment]
> **Describe the bug**
> When using multiple series, I tried to color the lines using SetSeriesOptions for each series, but this resulted in both series having the same options.
> 
> using v2.2.1
> 
> **To Reproduce:**
> Create an charts project from the line sample, and structure it as follows
> 
> ```
>         line := charts.NewLine()
> 
> 	line.SetXAxis(getDates(d)).AddSeries("series1", getVals(d)).
> 		SetSeriesOptions(
> 			charts.WithLabelOpts(opts.Label{
> 				Show: false,
> 			}),
> 			charts.WithAreaStyleOpts(opts.AreaStyle{
> 				Color:   "#0465db",
> 				Opacity: 0.3,
> 			}),
> 			charts.WithLineChartOpts(opts.LineChart{
> 				Smooth: true,
> 			}),
> 			charts.WithLineStyleOpts(opts.LineStyle{
> 				Color: "#1cace6",
> 			}),
> 		)
> 
> 	 line.AddSeries("series2", getVals(d2)).
> 		SetSeriesOptions(
> 			charts.WithLabelOpts(opts.Label{
> 				Show: false,
> 			}),
> 			charts.WithLineChartOpts(opts.LineChart{
> 				Smooth: true,
> 			}),
> 			charts.WithLineStyleOpts(opts.LineStyle{
> 				Color: "#2EFEF7",
> 			}),
> 		)
> ```
> 
> **Expected behavior**
> Using SetSeriesOptions for each series should result in the lineStyle, areaStyle etc. being applied for each line independently in the resulting e-charts html
> 
> **Screenshots**
> <img alt="test" width="1157" src="https://user-images.githubusercontent.com/40526638/99021221-0bf3cc80-2515-11eb-8e3d-e972edcab5f2.png">
> 
> Also wanted to say thanks again for writing this, as I found this project quite useful and easy to use


Thanks for the support

**Comment by chenjiandongx** [comment]
Docs have been updated https://github.com/go-echarts/go-echarts/commit/b2e3d8aa401f9374ca2d3b22ebafc7a5de0125c4
