### ISSUE TITLE
Suggestion: community wiki

### ISSUE THREAD

**Issue by jacksgt** [go-echarts/go-echarts#133]
Hello and thank you for this awesome library!

Especially after the release of v2, I think it would be helpful to have a community wiki (i.e. enable the Github wiki), so people can easily contribute examples, tutorials, documentation etc.

I am aware that there exists https://github.com/go-echarts/examples and I also want to mention that the README of this project is really excellent (straight to the point and very helpful for getting started!). The wiki is just a suggestion. :-)

**Comment by chenjiandongx** [comment]
@jacksgt thanks for your suggestions! Do you want to join us to perfect the wiki?

**Comment by Koooooo-7** [comment]
Thx for you advice, the docs is building on the way, and again, welcome to join us rich the docs. :)
