### ISSUE TITLE
Page rendering gives errors with same div ID

### ISSUE THREAD

**Issue by johnmillner** [go-echarts/go-echarts#139]
I'm having an issue rendering a page to html where the container.item.id fields are not unique - leading to syntax errors when displaying the page in a browser. 

cannot load pages: ex: 
* https://github.com/go-echarts/examples/blob/master/examples/page_center_layout.go
* https://github.com/go-echarts/examples/blob/master/examples/page_center_layout.go
* https://github.com/go-echarts/examples/blob/master/examples/page_flex_layout.go

gives errors where the first chart renders, but the others do not

![image](https://user-images.githubusercontent.com/5456241/99894776-811d7b00-2c54-11eb-8b13-c172c31bb499.png)

error messages:
```
Loaded claygl, version 1.2.1
echarts-gl.min.js:1 Loaded echarts, version 4.1.0
page_none_layout.html:30 Uncaught SyntaxError: Identifier 'goecharts_MZqBadxvuKyl' has already been declared
page_none_layout.html:41 Uncaught SyntaxError: Identifier 'goecharts_MZqBadxvuKyl' has already been declared
page_none_layout.html:52 Uncaught SyntaxError: Identifier 'goecharts_MZqBadxvuKyl' has already been declared
page_none_layout.html:74 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:85 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:96 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:107 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:118 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:129 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:140 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:151 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:162 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:173 Uncaught SyntaxError: Identifier 'goecharts_mhjEmTCPRtms' has already been declared
page_none_layout.html:184 
```

i also noticed this issue trying to recreate the issue on my project

playing around with the generated html - it looks like the generated id for each chart in the page is not unique
manually altering that id for each chart seems to fix the issue.

playing around some more - sometimes the unique ids are different while randomly rerunning the script
i think potentially the random id generation needs to be a little more random

I tried looking through the source to determine if this was a PR I could make, but my understanding of the render-er is a bit beyond me :( 

moved the examples since i believe this is an issue within the code and not the examples themselves - https://github.com/go-echarts/examples/issues/25

**Comment by chenjiandongx** [comment]
@johnmillner Try to upgrade go-echarts to v2.2.3, the new version had fixed the same-id issue on windows OS

**Comment by johnmillner** [comment]
That did the trick - thanks @chenjiandongx!
