### ISSUE TITLE
Suggestion: Intersection plots

### ISSUE THREAD

**Issue by MeHelmy** [go-echarts/go-echarts#142]
First, thank you all for your efforts.

Are there any plots/charts supported by go-echarts to represent data intersection? 

For example one of the most used is UpSet plots (Used in both Python and R).

https://pypi.org/project/UpSetPlot/
https://www.r-graph-gallery.com/upset-plot.html

Thanks,
Medhat

**Comment by Koooooo-7** [comment]
There is no plots/charts supported to represent data intersection so far. :(
IIRC, the library [echarts](https://github.com/apache/incubator-echarts) that we used has removed Venn map either since v3.0.

**Comment by MeHelmy** [comment]
@Koooooo-7  Do you know if any other packages support it?

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Do you know if any other packages support it?

I have no idea if any other packages can make it in Go. 😅 
There r some libs in other languages tho. Hope this helps.
- [upsetjs](https://github.com/upsetjs/upsetjs)
- [py-upset](https://github.com/ImSoErgodic/py-upset)
-  `matplotlib`
-  `pyvenn`

**Comment by MeHelmy** [comment]
> > @Koooooo-7 Do you know if any other packages support it?
> 
> I have no idea if any other packages can make it in Go. 😅
> There r some libs in other languages tho. Hope this helps.
> 
>     * [upsetjs](https://github.com/upsetjs/upsetjs)
> 
>     * [py-upset](https://github.com/ImSoErgodic/py-upset)
> 
>     * `matplotlib`
> 
>     * `pyvenn`

This is I know, but I am developing a tool using GO, so it is nonsense to use other packages/language to perform the task!
