### ISSUE TITLE
How to add chart to my template anywhere I want?

### ISSUE THREAD

**Issue by mateusscheper** [go-echarts/go-echarts#145]
Hi! 

Sorry if this is a dumb question, but how can I add the generated chart exactly where I want in my html? Without having to generate a HTML file, if possible.
The best I found is chart.render(w), but it renders at the top of the page, and I need it inside a specific DIV.

Example:
```
{{define "Index"}}
{{template "Navbar"}}
    <div class="main-container">
        <!-- Add the chart here (maybe using {{.}} to call the chart?) -->
    </div>
{{template "Footer"}}
{{end}}

```

Thanks in advance!

**Comment by mateusscheper** [comment]
Hello... anyone?

**Comment by chenjiandongx** [comment]
There is an example to customize your own template. https://github.com/go-echarts/examples/blob/master/examples/renderer.go

**Comment by mateusscheper** [comment]
I tried that one and it didn't work, but I probably implemented it wrong.
I'll try again.
Thanks!
