### ISSUE TITLE
Image Rendering Of Chart

### ISSUE THREAD

**Issue by bonedaddy** [go-echarts/go-echarts#148]
Is there a way to render charts via images as opposed to serving it via html?

**Comment by SteffenMahler** [comment]
You can write your own renderer as described in this blog:
https://blog.cubieserver.de/2020/how-to-render-standalone-html-snippets-with-go-echarts/

It helped me a lot to work nicely with revel and go-echarts.

**Comment by Koooooo-7** [comment]
Hi @bonedaddy , plz try [go-echarts/snapshot-chromedp](https://github.com/go-echarts/snapshot-chromedp)
