### ISSUE TITLE
question: example of dynamically adding bars to kline over time?

### ISSUE THREAD

**Issue by glycerine** [go-echarts/go-echarts#156]
Hello! go-echarts looks very interesting.

I wonder, is there an example of how to dynamically add data to a chart as time passes?  For example, in the kline charts, as new bars arrive it would be nice to plot them.

If you could suggest how to do this, or even provide a little example code, or even just point out what would need to be done, that would be great.

**Comment by daviFrag** [comment]
In order to dinamically change the chart you need to modify the current html in the page. You can do it with a javascript function witch receive some data ( implement websoket or with simple request) and modify the script that go-echarts has proviously generated.

**Comment by glycerine** [comment]
ok. thank you.
