### ISSUE TITLE
BarStack不能正常显示

### ISSUE THREAD

**Issue by yangqt** [go-echarts/go-echarts#191]
你好，
设置柱状图堆叠模式，图不能显示出来，示例中的barStack函数也运行不出来效果。

**Comment by chenjiandongx** [comment]
你用的是最新的 commit 的代码吗

**Comment by yangqt** [comment]
是最新的v2版本，那天画不出来，最后切前一个版本了

**Comment by zhangyongInfo** [comment]
请问这个问题解决了吗

**Comment by Koooooo-7** [comment]
fixed, plz try the latest release.
