### ISSUE TITLE
V2版本Legend取消了Type: "scroll"

### ISSUE THREAD

**Issue by chaokw** [go-echarts/go-echarts#195]
V2版本Legend取消了Type: "scroll"，在大量Legend的情况下，显示很糟糕，请问有什么替代方案吗？V1切V2碰到的这个问题，谢谢

**Comment by chenjiandongx** [comment]
@chaokw 这周末发布一个新版本 新增该功能

**Comment by chaokw** [comment]
Thanks

**Comment by chenjiandongx** [comment]
@chaokw master 分支已经更新了
