### ISSUE TITLE
不能保存为img？？？

### ISSUE THREAD

**Issue by 1450793561** [go-echarts/go-echarts#213]
不能保存为img？？？

**Comment by 1450793561** [comment]
hope 增加图片支持

**Comment by Koooooo-7** [comment]
Hi, plz try this above.
```go
func saveImg() *charts.Bar {
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "toolbox options"}),
		charts.WithToolboxOpts(opts.Toolbox{
			Show: true,
			Feature: &opts.ToolBoxFeature{
				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
					Show:  true,
					Type:  "png",
					Title: "Anything you want",
				},
			}},
		),
	)
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	return bar
}
```

**Comment by rudy-tao** [comment]
> Hi, plz try this above.
> 
> ```go
> func saveImg() *charts.Bar {
> 	bar := charts.NewBar()
> 	bar.SetGlobalOptions(
> 		charts.WithTitleOpts(opts.Title{Title: "toolbox options"}),
> 		charts.WithToolboxOpts(opts.Toolbox{
> 			Show: true,
> 			Feature: &opts.ToolBoxFeature{
> 				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
> 					Show:  true,
> 					Type:  "png",
> 					Title: "Anything you want",
> 				},
> 			}},
> 		),
> 	)
> 	bar.SetXAxis(weeks).
> 		AddSeries("Category A", generateBarItems()).
> 		AddSeries("Category B", generateBarItems())
> 	return bar
> }
> ```

有好的办法可以直接导出文件吗

**Comment by Koooooo-7** [comment]
Unfortunately, there is no official interface to do the trick, u make need some extra program for now.

**Comment by sjm1327605995** [comment]
I see that this library github.com/vicanso/go-charts/v .can convert echarts options to png export. The effect is consistent. I hope it can be used as a reference for image export

**Comment by Koooooo-7** [comment]
Hi @1450793561 , plz try  [go-echarts/snapshot-chromedp](https://github.com/go-echarts/snapshot-chromedp)
