### ISSUE TITLE
如何显示图例

### ISSUE THREAD

**Issue by dbadylan** [go-echarts/go-echarts#216]
![20220111161519](https://user-images.githubusercontent.com/46683377/148905502-96471fe3-0a44-4d8f-a69b-eb5e016a7ac2.png)

如上图，红框部分的图例怎么显示出来，谢谢！

**Comment by l-we** [comment]
全局属性添加 Legend 设置

```
line.SetGlobalOptions(
	charts.WithLegendOpts(opts.Legend{Show: true}),
)
```

**Comment by dbadylan** [comment]
好的，感谢！
