### ISSUE TITLE
Candlestick brush (aka full kline chart)

### ISSUE THREAD

**Issue by bygui86** [go-echarts/go-echarts#219]
Hi guys,

I think here we miss a pretty important feature: [Candlestick brush](https://echarts.apache.org/examples/en/editor.html?c=candlestick-brush) in Apache Echarts examples (aka full kline chart).

![candlestick-brush](https://user-images.githubusercontent.com/22518997/149770884-8a08d951-2a3b-47cf-a693-37ada2fdfe09.png)

In issue #169 @alaingilbert showed a simple yet interesting enhancement to allow building the candlestick-brush.
Here the link: https://github.com/alaingilbert/go-echarts/commit/c80db93de77a03040462ede3a5c60bb0954e05ba
And here an practical example: https://github.com/go-echarts/go-echarts/issues/169#issuecomment-1014285680

Alternative it would be good to evaluate the integration of [iamjinlei/go-tachart](https://github.com/iamjinlei/go-tachart).

**Comment by Koooooo-7** [comment]
closed via #241
