### ISSUE TITLE
xAxis does not display fully

### ISSUE THREAD

**Issue by madneal** [go-echarts/go-echarts#228]
When tried to set xAxis with some Chinese words, there would be some xAxis does not display and even be cut.

![image](https://user-images.githubusercontent.com/12164075/154900264-2903a95a-504c-47d3-955c-850d075bd532.png)

I tried to set the width and height, but it does not work.

```
	bar.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{
			Width: "1000px",
			Height: "800px",
		}),
		charts.WithXAxisOpts(opts.XAxis{
			AxisLabel: &opts.AxisLabel{Show: true, Rotate: 75},
		}),
	)
```

**Comment by karageee** [comment]
Hello, do you have the solution for this problem?

**Comment by madneal** [comment]
I forget the soultion. But I remember it can be fixed by some configuration.

**Comment by karageee** [comment]
> 请问兄弟还记得配置哪个东西可以吗 找了好久没找到 我测试了一下 除了拉长这个图片的画布没别的办法了（

The only way I could solve it was by configuring the width of the chart as a whole. The reason it become like that was because the text couldn't fit the provided width.

**Comment by K0zero** [comment]
> > 请问兄弟还记得配置哪个东西可以吗 找了好久没找到 我测试了一下 除了拉长这个图片的画布没别的办法了（
> 
> I used a different chart library from https://github.com/wcharczuk/go-chart The only way I could solve it was by configuring the width of the chart as a whole. The reason it become like that was because the text couldn't fit the provided width.
> 
> for example:
> 
> ```go
> graph := chart.BarChart{
> 		Title:      "Total Cost by Service",
> 		TitleStyle: chart.Style{},
> 		Background: chart.Style{
> 			Padding: chart.Box{
> 				Top: 40,
> 			},
> 		},
> 		Height: 512,
> 		Width:  1700,
> 		Bars:   amounts,
> 		XAxis: chart.Style{
> 			StrokeWidth: 2,
> 			StrokeColor: chart.GetDefaultColor(0).WithAlpha(100),
> 			Hidden:      false,
> 		},
> 		YAxis: chart.YAxis{
> 			Style: chart.Style{
> 				StrokeWidth: 2,
> 				StrokeColor: chart.GetDefaultColor(0).WithAlpha(100),
> 				Hidden:      false,
> 			},
> 			Ticks: create_Ylabel(highest, []chart.Tick{}),
> 		},
> 	}
> ```
> 
> it's not a clean code but the main idea still stands. You have to config the Width of the barchart.

yeah the only way is to increase the width i guess
i also tried addJavascript but it didt work
