### ISSUE TITLE
如何把chart渲染为svg 或其他格式的image

### ISSUE THREAD

**Issue by lissali** [go-echarts/go-echarts#23]

**Comment by ElectricBubble** [comment]
> ## 远程引用
> go-echarts 没有自带自身所需要引用的 JS/CSS 文件，均是通过远程引用，引用的地址为 http://chenjiandongx.com/go-echarts-assets/assets/，这是通过我的一个项目 [go-echarts-assets](https://github.com/chenjiandongx/go-echarts-assets) 实现的。

所以，可以通过从[ECharts.js官网](https://www.echartsjs.com/builder.html)定制下载支持**SVG 渲染**的js版本，替换远程引用仓库里的文件，即可实现svg

**Comment by linuxMengfan** [comment]
@ElectricBubble 
我按你的提示 进行了操作. 修改了 base.go AssetsHost参数后没有生效。

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-snapshot  ：）
