### ISSUE TITLE
charts WithYAxisOpts AxisLabel Formatter Set Function Not Working

### ISSUE THREAD

**Issue by canghai908** [go-echarts/go-echarts#234]
The code does not work properly
`
var  Formatter =`
function(value) {
      if ((value / (1024 * 1024 * 1024)) > 10) {
        return (value / (1024 * 1024 * 1024)).toFixed(2) + " Gbps";
      } else if ((value / (1024 * 1024)) > 10) {
        return (value / (1024 * 1024)).toFixed(2) + " Mbps";
      } else if ((value / (1024)) > 10) {
        return (value / (1024)).toFixed(2) + " Kbps";
      } else {
        return value + " bps";
      }
    }
`
charts.WithYAxisOpts(opts.YAxis{
			AxisLabel: &opts.AxisLabel{
				Show:      true,
				Formatter: opts.FuncOpts(Formatter )},
		}),
`
result
![image](https://user-images.githubusercontent.com/1450994/162660010-5f311162-7705-4706-bece-65df805840f0.png)
source html
![image](https://user-images.githubusercontent.com/1450994/162660070-562c40ef-466e-46b2-9563-c0a80e50637c.png)

**Comment by Koooooo-7** [comment]
Hi @canghai908 , it seems the func string format issue.
```go
var Formatter = "	function(value) { if ((value / (1024 * 1024 * 1024)) > 10) { return (value / (1024 * 1024 * 1024)).toFixed(2) +  'Gbp';" + " } else if ((value / (1024 * 1024)) > 10) { return (value / (1024 * 1024)).toFixed(2) + 'Mbps'; } else if ((value / (1024)) > 10) { return (value / (1024)).toFixed(2) + 'Kbp'; } else { return value + 'bp'; } }"

```
