### ISSUE TITLE
save charts as image

### ISSUE THREAD

**Issue by mandotrin** [go-echarts/go-echarts#235]
Does someone can provide a working example to save charts as png ? I set the Feature 'SaveAsImage' but it's still produce a .html file.

```
func createLineChart() *charts.Line {
	line := charts.NewLine()

	// set some global options like Title/Legend/ToolTip or anything else
	line.SetGlobalOptions(
		charts.WithLegendOpts(opts.Legend{
			Show:   true,
			Type:   "plain",
			Left:   "center",
			Bottom: "0%"},
		),
		charts.WithTitleOpts(opts.Title{
			Title: "Some nice title",
			Left:  "center"},
		),
		charts.WithToolboxOpts(opts.Toolbox{
			Show: true,
			Feature: &opts.ToolBoxFeature{
				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
					Show:  true,
					Type:  "png",
					Title: "png title",
				},
			}},
		),
	)

	line.SetXAxis(weeks).AddSeries("Inquerys",generateLineItems())

	return line
}

func main() {
	line := createLineChart()
	// Where the magic happens
	f, err := os.Create("line.png")
	if err != nil {
		log.Fatal(err)
	}
	line.Render(f)

}
```

Thank you

**Comment by lrtxpra** [comment]
it looks like that 'SaveAsImage' option does not mean that you can save image on the server, but display icon of download on web page.
I am looking for method of saving as image on the server too.......

**Comment by lrtxpra** [comment]
> Does someone can provide a working example to save charts as png ? I set the Feature 'SaveAsImage' but it's still produce a .html file.
> 
> ```
> func createLineChart() *charts.Line {
> 	line := charts.NewLine()
> 
> 	// set some global options like Title/Legend/ToolTip or anything else
> 	line.SetGlobalOptions(
> 		charts.WithLegendOpts(opts.Legend{
> 			Show:   true,
> 			Type:   "plain",
> 			Left:   "center",
> 			Bottom: "0%"},
> 		),
> 		charts.WithTitleOpts(opts.Title{
> 			Title: "Some nice title",
> 			Left:  "center"},
> 		),
> 		charts.WithToolboxOpts(opts.Toolbox{
> 			Show: true,
> 			Feature: &opts.ToolBoxFeature{
> 				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
> 					Show:  true,
> 					Type:  "png",
> 					Title: "png title",
> 				},
> 			}},
> 		),
> 	)
> 
> 	line.SetXAxis(weeks).AddSeries("Inquerys",generateLineItems())
> 
> 	return line
> }
> 
> func main() {
> 	line := createLineChart()
> 	// Where the magic happens
> 	f, err := os.Create("line.png")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	line.Render(f)
> 
> }
> ```
> 
> Thank you

it looks like that 'SaveAsImage' option does not mean that you can save image on the server, but display icon of download on web page.
I am looking for method of saving as image on the server too.......

**Comment by mandotrin** [comment]
in the meantime i figured it out - see the following for a working example. hope this is helpful for someone
```
// generate random data for bar chart
func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func main() {
	file := "bar"
	// create a new bar instance
	bar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "My first bar chart generated by go-echarts",
			Subtitle: "It's extremely easy to use, right?",
		}),
		charts.WithLegendOpts(opts.Legend{
			Show:   true,
			Type:   "plain",
			Left:   "center",
			Bottom: "0%",
		}))

	// Put data into instance
	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	// Where the magic happens
	f, _ := os.Create(file + ".html")
	err := bar.Render(f)
	if err != nil {
		log.Fatal(err)
	}
	savePNG(file)
}

func savePNG(file string) {
	// get full path of file
	abs, _ := filepath.Abs(file)

	// create context
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	// screenshot buffer
	var buf []byte

	// capture entire browser viewport, returning png with quality=100
	task := chromedp.Tasks{
		// use file:// for a local file
		chromedp.Navigate("file://" + abs + ".html"),
		// set resolution for screenshot
		chromedp.EmulateViewport(1200, 800),
		// take screenshot
		chromedp.FullScreenshot(&buf, 100),
	}

	// run tasks
	if err := chromedp.Run(ctx, task); err != nil {
		log.Fatal(err)
	}
	// write png
	if err := ioutil.WriteFile(abs+".png", buf, 0644); err != nil {
		log.Fatal(err)
	}
}
```
