### ISSUE TITLE
go-echarts-example 中的 stack bar 示例失效

### ISSUE THREAD

**Issue by allanpk716** [go-echarts/go-echarts#236]
如题，https://github.com/go-echarts/examples/blob/c1dea2301ce9a9d8be132eb01c5d72e2d4611f83/examples/bar.go#L261

测试这个堆叠效果的时候发现官方提供的也无法正确显示输出到文件了，是换方法了吗？没看到有相关的 issues

**Comment by Koooooo-7** [comment]
Hi @allanpk716 , 使用example里面的代码我没有办法重现这个问题，可以帮忙检查看看console有没有输出更多的错误信息。

**Comment by Koooooo-7** [comment]
fixed, plz upgrade the latest version and have a check. :)
