### ISSUE TITLE
Stacked bars error

### ISSUE THREAD

**Issue by lrfuentesw** [go-echarts/go-echarts#248]
Hi, if i change this part of the bar example
```go
// Put data into instance
	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
```
to this
```go
// Put data into instance
	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems()).
                SetSeriesOptions(charts.WithBarChartOpts(opts.BarChart{
		 	Stack: "stackA",
		}))
```
The graph doesnt render. The console shows:

> Uncaught Error: series.type should be specified.
    at Zi.t.getClass (echarts.min.js:21:35723)
    at i.<anonymous> (echarts.min.js:21:302258)
    at Array.forEach (<anonymous>)
    at d (echarts.min.js:21:1663)
    at i.<anonymous> (echarts.min.js:21:302160)
    at t.topologicalTravel (echarts.min.js:21:298289)
    at i.mergeOption (echarts.min.js:21:301930)
    at i.Sa (echarts.min.js:21:68004)
    at i.resetOption (echarts.min.js:21:301446)
    at i.setOption (echarts.min.js:21:301241)

What should i modify so i can have stacked bars?

**Comment by Koooooo-7** [comment]
Hi @lrfuentesw , I can not reproduce it. could u plz provide more info about it ?
FYI. it is my test case.
```go
	
	weeks   = []string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}
	bar := charts.NewBar()
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems()).
		SetSeriesOptions(charts.WithBarChartOpts(opts.BarChart{
			Stack: "stackA",
		}))

```
<img width="854" alt="image" src="https://user-images.githubusercontent.com/33706142/197671745-34a05cbf-ddd2-44bc-98e4-1c3015c992aa.png">

**Comment by lrfuentesw** [comment]
Hi
This is the code i'm trying:
```golang
package main

import (
	"math/rand"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// generate random data for bar chart
func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func main() {
	// create a new bar instance
	bar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	// Put data into instance
	weeks := []string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems()).
		SetSeriesOptions(charts.WithBarChartOpts(opts.BarChart{
			Stack: "stackA",
		}))
	// Where the magic happens
	f, _ := os.Create("bar.html")
	bar.Render(f)
}
```
And this is the error i get from the generated html:

> Uncaught Error: series.type should be specified.
    at Zi.t.getClass (echarts.min.js:21:35723)
    at i.<anonymous> (echarts.min.js:21:302258)
    at Array.forEach (<anonymous>)
    at d (echarts.min.js:21:1663)
    at i.<anonymous> (echarts.min.js:21:302160)
    at t.topologicalTravel (echarts.min.js:21:298289)
    at i.mergeOption (echarts.min.js:21:301930)
    at i.Sa (echarts.min.js:21:68004)
    at i.resetOption (echarts.min.js:21:301446)
    at i.setOption (echarts.min.js:21:301241)

Thanks for the reply

**Comment by Koooooo-7** [comment]
Hi, I tried the code u provide, it works fine on my side based on current go-echarts dev code, i doubt there have some fix on this in recently after v2, may have a patch soon if needs.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/33706142/197765334-65492dae-f581-4810-be90-4e517851f3b3.png">

**Comment by lrfuentesw** [comment]
Hi
I was using the last tag versión. Now i'm using the latest code and it's working fine.
Thank you
