### ISSUE TITLE
copy example to others,packr load templates error:CreateFile D:\...

### ISSUE THREAD

**Issue by robinsoon** [go-echarts/go-echarts#25]
Compile example  and test the exe file on others

### ` packr load templates error:CreateFile D:\Go\src\github.com\chenjiandongx\go-echarts\templates\routers.html`

the **Path** in  others PC  "...\go-echarts\templates\routers.html" cannot find .
**Why is absolute path rather than relative path?**
Can't I copy the past together and run it locally?

```
package templates

import (
	"io/ioutil"
	"log"
	"net/http"

	"github.com/gobuffalo/packr"
)

var BaseTpl, ChartTpl, HeaderTpl, PageTpl, RoutersTpl string

func init() {
	box := packr.NewBox(".")

	var err error
	BaseTpl, err = box.FindString("base.html")
	ChartTpl, err = box.FindString("chart.html")
	HeaderTpl, err = box.FindString("header.html")
	PageTpl, err = box.FindString("page.html")
	RoutersTpl, err = box.FindString("routers.html")

	if err != nil {
		log.Printf("packr load templates error: %v", err)
	}
}
```

ps:  Tracing request for /favicon.ico
I didn't find this icon on the page. Does it work?

**Comment by ElectricBubble** [comment]
Try executing the script file first 

Linux/MacOS
```bash
$ cd $GOPATH/src/github.com/chenjiandongx/go-echarts
$ ./doPackr.sh
```

Windows
```dos
$ cd %GOPATH%\src\github.com\chenjiandongx\go-echarts
$ doPackr.bat
```
