### ISSUE TITLE
assets: go-echarts versus apache echarts

### ISSUE THREAD

**Issue by ehdis** [go-echarts/go-echarts#251]
As they are included in the rendered output of go-echarts - I wonder about these assets files:

https://github.com/go-echarts/go-echarts/blob/ad9b214d3d71d5a1a0e02c2a706df9b23acdcbf6/opts/global.go#L37

Are they synchronised with apache echarts releases?

https://github.com/go-echarts/go-echarts-assets shows quite old commits only. 

Thanks for any feedback.

**Comment by Koooooo-7** [comment]
Hi @ehdis , we upgrade echarts to `v5.4.3` now.
