### ISSUE TITLE
bar 能否支持base 属性？

### ISSUE THREAD

**Issue by taoisym** [go-echarts/go-echarts#252]
![image](https://user-images.githubusercontent.com/23164750/196035383-86af96a4-a9f8-4d84-8e25-f2d772fe826d.png)
like plotly
`var trace1 = {
  x: ['giraffes', 'orangutans', 'monkeys'],
  y: [20, 14, 23],
  base:20,
  name: 'SF Zoo',
  type: 'bar'
};

var trace2 = {
  x: ['giraffes', 'orangutans', 'monkeys'],
  y: [12, 18, 29],
  name: 'LA Zoo',
  base:10,
  type: 'bar'
};

var data = [trace1, trace2];

var layout = {barmode: 'group'};

Plotly.newPlot('myDiv', data, layout);
`

**Comment by Koooooo-7** [comment]
请问可以贴出来echarts对应的`base`相关的配置文档吗。

**Comment by Koooooo-7** [comment]
missing feedback.
