### ISSUE TITLE
折线图中使用 SetGlobalOptions(WithColorsOpts{})无效

### ISSUE THREAD

**Issue by Suvian-wy** [go-echarts/go-echarts#254]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/56574401/196885491-17d0109e-4d7a-4f76-ab87-884d849061a4.png">
在html中没有出现color的配置

**Comment by Koooooo-7** [comment]
Remove the `Initialization theme config` to enable custom color settings.

**Comment by Suvian-wy** [comment]
thanks
