### ISSUE TITLE
Generic interface that all chart types adhere to

### ISSUE THREAD

**Issue by amlwwalker** [go-echarts/go-echarts#256]
I want to create a bunch of functions that work regardless of chart type. I realise I could use Go generics, but hoping there is an interface or something that all charts adhere to so I can just use that? 
The idea being I can pass any chart type to a function to add a legend or whatever
Is there an example potentially?
Thanks

**Comment by Koooooo-7** [comment]
Hi @amlwwalker , I guess there is no those generics config for charts no matter what type it is.
