### ISSUE TITLE
这样做的好处是什么？

### ISSUE THREAD

**Issue by colatea** [go-echarts/go-echarts#26]
为什么不直接提供数据让前端渲染？这样做的好处在哪里？哪些场景需要用到？

**Comment by lvxin0315** [comment]
> 为什么不直接提供数据让前端渲染？这样做的好处在哪里？哪些场景需要用到？

其实这样也挺方便的，同时少一些前端的工作量，我尝试的用了一下~一套地址给其他项目嵌套用，目前还算可以
