### ISSUE TITLE
Bar3D uses scatter3D rather than bar3D for type?

### ISSUE THREAD

**Issue by darrenparkinson** [go-echarts/go-echarts#263]
Hi,

It looks like Bar3D is using scatter3D rather than bar3D?

```go
c.addSeries(types.ChartScatter3D, name, data, options...)
```
https://github.com/go-echarts/go-echarts/blob/f66a5da680f3be32384dfc4c591fe09c0527887f/charts/bar3d.go#L28

Thanks.

**Comment by Koooooo-7** [comment]
Hi @darrenparkinson , thx for this, fixed in #170 .
