### ISSUE TITLE
How do you have sporadic data?

### ISSUE THREAD

**Issue by JohnAllen** [go-echarts/go-echarts#265]
Say I want to plot stock orders on a chart. These don't happen every line/row/minute. How do you have a chart with data plotted on some lines but not all.
I note that there is an example in the issues for this that does not work because `withEncode` or whatever it is is no longer part of the library I think.

**Comment by Koooooo-7** [comment]
Hi @JohnAllen , `withEncode` is literally inside here.
I'm not quite sure the description of the charts you want.
Could you provide a sample pic or codebase (mock code is okay). I would check how we could do the trick.
