### ISSUE TITLE
New Tag?

### ISSUE THREAD

**Issue by Roemer** [go-echarts/go-echarts#269]
Is there any chance to get new tags out? There were plenty of changes already, some which are pretty important (eg. the `WithGridOpts`). Is there any plan to get new versions out soon so I don't have to reference git commit hashes as version?

**Comment by Koooooo-7** [comment]
Hi @Roemer , we tag a new one `v2.2.5` now.  plz have a try on it. :)

**Comment by Roemer** [comment]
Many thanks.
