### ISSUE TITLE
Custom render function

### ISSUE THREAD

**Issue by lublak** [go-echarts/go-echarts#270]
I would like to render these diagrams into a pdf file.
Is there a possibility to intercept the drawing commands?
Like for example
drawRect?

As a whole example.

```go
type Render interface {
    drawRect()
}
diagram.Render(instanceOfRender)
```

alternative: https://github.com/go-echarts/go-echarts/issues/165

**Comment by Koooooo-7** [comment]
Hi @lublak , I hope I could response earlier.
I'm not very clear about your question.
Do you mean you wanna implement you custom render? thats viable.
Implement the `Renderer` interface.

**Comment by lublak** [comment]
@Koooooo-7 I think I misunderstood the project back then.
go-echarts is, if I see correctly, just a wrapper over echarts. In general, the idea here was that a graphic is generated from go. This is hardly possible with this project, as the charts are not drawn here, but the data is transferred to echarts js. (js/html).
My thought was that this project is a native port of echarts.

**Comment by Koooooo-7** [comment]
Hi @lublak , you are right that the go-echarts is just the generator for echarts specific configs.
You could try to export it as a PDF from a byte stream, such as [snapshot-chromedp](https://github.com/go-echarts/snapshot-chromedp) captures the pic.

**Comment by lublak** [comment]
I don't know if it's a good solution to be dependent on external software. It was ‘about’ software that was supposed to generate graphics independently. However, I no longer need it at the moment. I think the issue can also be closed here, as it is rather out of scope.
If required, rendering via a browser would of course be possible. Here https://github.com/webview/webview_go could also be very practical.
