### ISSUE TITLE
Bar can not show label

### ISSUE THREAD

**Issue by awinlei** [go-echarts/go-echarts#271]
![image](https://user-images.githubusercontent.com/4607279/218395103-4fb30a0f-4bac-4566-837a-466be67b175a.png)
this search button in bar can not work

**Comment by ysicing** [comment]
Same with Line after v2.2.5.

Rollback to version v2.2.4

**Comment by Koooooo-7** [comment]
Hi @awinlei , @ysicing , thx for this. Gonna fix it by set the `show=true` by default when there has config the `Legend`.
For now, it needs manully set the `charts.WithLegendOpts(opts.Legend{Show: true}),`.
