### ISSUE TITLE
Error Bars?

### ISSUE THREAD

**Issue by nathanhack** [go-echarts/go-echarts#289]
Are error bars supported for bar or scatter charts? 
Maybe something like https://echarts.apache.org/examples/en/editor.html?c=custom-error-scatter or https://echarts.apache.org/examples/en/editor.html?c=custom-error-bar.

**Comment by Koooooo-7** [comment]
Hi @nathanhack , thx for your propose on this.
unfortunately，this feat seems hard to implement for now, since it manipulates data more on `echarts instance`, go-echarts is weak on it.

**Comment by mitar** [comment]
I would also need that. I think a `Custom` chart which inherits `RectChart` and provides `renderItem` as a string should be good enough for this, no?

**Comment by Koooooo-7** [comment]
> renderItem

Hi @mitar , glad to hear that you have a idea on it.
I'm not quite sure what the `Custom` chart gonna looks like. Maybe you could have a try on it, add the `renderItem` option and insert the string.
Besides, I think the `renderItem` as a string (a JS func string) is cumbersome on current chart builders go-echarts provided, if it is quite complex.

**Comment by mitar** [comment]
I made https://github.com/go-echarts/go-echarts/pull/325. It seems it works.

**Comment by Koooooo-7** [comment]
Hi @nathanhack  I think we don't need those level customized part support for now.
If user do wanna have those requirements, consider implement it with echarts directly.
Put lots of JSFunc string in go-echarts is no different to write the whole echarts stuff.
