### ISSUE TITLE
Using `render.MustTemplate` with chart causes parsing error

### ISSUE THREAD

**Issue by LJ-Software** [go-echarts/go-echarts#292]
When attempting to use the base template with my chart I get this template parsing error `function "safeJS" not defined`. This led me to see that the `render.MustTemplate` function does not add the function `safeJS` to the template *before* calling `parse` on the template.

https://pkg.go.dev/text/template#Template.Funcs
States that
> Funcs adds the elements of the argument map to the template's function map. It must be called before the template is parsed.
I've tested making the tweak to `render.MustTemplate` to abide by this requirement and it works correctly now.

**Comment by Koooooo-7** [comment]
Hi @LJ-Software , could plz provide a tiny reproduce demo? thx.

**Comment by LJ-Software** [comment]
@Koooooo-7 Sure, I was able to get the same error with this code:
```golang
package main

import (
  "bytes"
  "log"
  
  "github.com/go-echarts/go-echarts/v2/charts"
  "github.com/go-echarts/go-echarts/v2/render"
  "github.com/go-echarts/go-echarts/v2/templates"
)

func main() {
  graph := charts.NewGraph() =>  *charts.Graph
  contents := []string{templates.BaseTpl, templates.ChartTpl, templates.HeaderTpl}
  tpl := render.MustTemplate("chart", contents) 
  buf := new(bytes.Buffer) =>  *bytes.Buffer
  if err := tpl.ExecuteTemplate(buf, "chart", graph); err != nil { 
    log.Panic("could not execute template")
  }
}
  ```

**Comment by LJ-Software** [comment]
Would it be possible to get a new release tag off the master branch with this fix in? @Koooooo-7

**Comment by Koooooo-7** [comment]
> Would it be possible to get a new release tag off the master branch with this fix in? @Koooooo-7

No prob, I gonna have a patch release on it, and you could tag the commit id as workaround.

**Comment by Koooooo-7** [comment]
FYI @LJ-Software , `v2.2.7` released.
