### ISSUE TITLE
我这出现了极端值不展示的情况

### ISSUE THREAD

**Issue by LJTian** [go-echarts/go-echarts#296]
情况如下：
1. 数据库中的数据平均值为 1 左右，数据量5000条，其中1-2条的值为9。
2. 对这些数据进行折线图展示与散点图展示后，找不到9对应的散点值或者曲线值，但是 Y 轴已经进行了延伸。
图如下：
![image](https://github.com/go-echarts/go-echarts/assets/86409955/286ec81e-a317-40e8-9eaa-d0e0ba6fe082)
![image](https://github.com/go-echarts/go-echarts/assets/86409955/7348831f-24c4-4d54-a094-18e95d443976)
sql 结果如下：
![image](https://github.com/go-echarts/go-echarts/assets/86409955/bfb888c3-89d5-4a47-bac2-59229e9b3378)
个人分析：
数据量大时，部分数据展示会丢失

**Comment by Koooooo-7** [comment]
Hi @LJTian , 可以提供一份脱敏数据和sample代码复现一下吗。

**Comment by LJTian** [comment]
当然。地址为：https://raw.githubusercontent.com/LJTian/openshift/main/src/cobra-curl-cli/data.csv。
代码可以查看 https://raw.githubusercontent.com/LJTian/openshift/main/src/cobra-curl-cli。
执行命令：
./go_build_cobra_curl_cli show -D="root:123456@tcp(127.0.0.1:3306)/logs?charset=utf8mb4&parseTime=True&loc=Local" -C=clientName_gBQNS

**Comment by ppd324** [comment]
每次渲染数据都得从数据库重新读取一遍，有没有更好的方法

**Comment by LJTian** [comment]
> 每次渲染数据都得从数据库重新读取一遍，有没有更好的方法

这个只是观测时，刷新页面加载。非业务自动触发，也不涉及到超多人使用，没有必要过渡开发，添加缓存功能。

**Comment by Koooooo-7** [comment]
Hi @LJTian ,  这个看上去和`echarts` 本身`x-y`的数据绑定有关系， 可能还需要具体看一下文档。
目前看到的现象是如果  `极值 > x轴切分数量`， 就会不展示。
比如data是5000个采样数据， x轴按照`5`分切分， 当极值所在的位置小于 1000时，能正常显示，大于1000时就丢失了。
所以临时的解决办法是设置`SetXAxis >= 数据长度` 即可， 比如
```go
         x := make([]int, 0)
	for i := 1; i <= 5000; i++ {
		x = append(x, i)
	}
	scatter.SetXAxis(x)
```


---
FYI

Echarts 本身复现 sandbox:   [Sandbox](https://codesandbox.io/s/fp3d33?file=/index.js)

Senario:

分别在 123 位置和 1555 ( > x 轴切分值） 的位置放置极值。


![image](https://github.com/go-echarts/go-echarts/assets/33706142/816ec420-59e8-4543-b86f-6445fcaed03c)

Code
```go
func generateScatterItems() []opts.ScatterData {
	items := make([]opts.ScatterData, 0)
	for i := 0; i < 5000; i++ {
		// specific data
		if i == 123 {
			items = append(items, opts.ScatterData{
				Value:        20.12,
				Symbol:       "roundRect",
				SymbolSize:   5,
				SymbolRotate: 5,
			})
			continue

		}

		// specific data
		if i == 1555 {
			items = append(items, opts.ScatterData{
				Value:        47.1555,
				Symbol:       "roundRect",
				SymbolSize:   5,
				SymbolRotate: 5,
			})
			continue

		}
		items = append(items, opts.ScatterData{
			Value:        randFloats(0.1, 1),
			Symbol:       "roundRect",
			SymbolSize:   5,
			SymbolRotate: 5,
		})
	}
	return items
}
func scatterBase() *charts.Scatter {
	scatter := charts.NewScatter()
	scatter.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "basic scatter example"}),
	)

	x := make([]int, 0)
	for i := 1; i <= 5000; i++ {
		x = append(x, i/5)
	}

	//for i := 1; i <= 5000; i++ {
	//	x = append(x, i)
	//}

	scatter.SetXAxis(x).
		AddSeries("Category A", generateScatterItems())
	return scatter
}


```

**Comment by LJTian** [comment]
问题找到了，感谢。

**Comment by LJTian** [comment]
这个问题，是否要进行关闭呢？

**Comment by Koooooo-7** [comment]
> 这个问题，是否要进行关闭呢？

no prob.
