### ISSUE TITLE
Upgrade to version echarts v5 ? 

### ISSUE THREAD

**Issue by dh1tw** [go-echarts/go-echarts#297]
Hi,
is there any reason why the used version of echarts is (the relatively old version) 4.3? 

At least the *polar bar chart* appears to be broken but fixed with latest echarts version (5.4.3). 
The behavior can be replicated by executing the example provided in PR #157.

Tnx!

**Comment by Koooooo-7** [comment]
Hi @dh1tw , sorry for the inconvenient. 

TBH, thats our mistake. we does not notice that we haven't finished upgrade the default asset of `echarts` up to date on our side yet. 😅 

As a workaround, you could do this tricky to use the echarts official resources, e.g `v5.4.3`, the latest.

- On page usage
```go
        page := components.NewPage()
	page.AssetsHost = "https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/"
```

- On single chart usage
```go
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{
			AssetsHost: "https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/",
		}),
        )

```

Once we finish the tests and update charts samples, we will upgrade this assets asap.

**Comment by dh1tw** [comment]
Thanks for the swift reply @Koooooo-7. I have already prepared a PR for adding polar line plots (very useful for drawing antenna patterns), but it only works with version 5. 

Looking forward to the update of the default asset to 5.x.!

**Comment by Koooooo-7** [comment]
> Thanks for the swift reply @Koooooo-7. I have already prepared a PR for adding polar line plots (very useful for drawing antenna patterns), but it only works with version 5.
> 
> Looking forward to the update of the default asset to 5.x.!

That would be great ! when we finish the upgrade,  I gonna ping you here, is that okay?
Or you could raise the PR with the `custom host` immediately is fine also, I could do the update on your works when we upgrade the assets ( if it is necessary, in other word,  I think using `custom host` would be a sample as well. )
 tia.

**Comment by Koooooo-7** [comment]
ping @dh1tw . Already upgrade to `v5.4.3`, plz go ahead. :)
