### ISSUE TITLE
The method name `Scatter.AddYAxis` is misleading.

### ISSUE THREAD

**Issue by updogliu** [go-echarts/go-echarts#30]
The method name `Scatter.AddYAxis` is misleading. It actually adding a data series.
For example, one can add (x, y) coordinates as two-element slices
```
zs := [][]float64{
	[]float64{1, 5},
	[]float64{2, 1},
	[]float64{8, 2},
	[]float64{9, 10},
	[]float64{15, 20},
}
scatter.AddYAxis("My Points", zs)
```
![image](https://user-images.githubusercontent.com/1288299/61352681-8fa99480-a8a0-11e9-849f-8d75497a5ad8.png)

**Comment by chenjiandongx** [comment]
`AddYAxis` adds a series data for y axis, there is another func named `ExtendYAxis`. May be it is what you nedd?

**Comment by updogliu** [comment]
The argument of `AddYAxis` goes to the `Data` field of the series (see the code snippet below). Why don't just call it `AddData`?
As you can see in my example, the argument of `AddYAxis` can specifies not only the `y` coordinates, but also the `x` coordinates.  

```
func (c *Scatter) AddYAxis(name string, yAxis interface{}, options ...seriesOptser) *Scatter {
	series := singleSeries{Name: name, Type: ChartType.Scatter, Data: yAxis}
	series.setSingleSeriesOpts(options...)
	c.Series = append(c.Series, series)
	c.setColor(options...)
	return c
}
```

**Comment by updogliu** [comment]
By the way, the example CANNOT be changed to 
```
scatter.AddXAxis([]float64{1, 2, 8, 9, 15}).AddYAxis("name", []float64{5, 1, 2, 10, 20})
```
The `AddXAxis` cannot add x coordinates of `value` type.

**Comment by chenjiandongx** [comment]
`AddYAxis` does not set x coordinates, only series data.If you want to add `x` coordinates of value type, you need specify axis-type, see option below

![image](https://user-images.githubusercontent.com/19553554/61383989-45490780-a8e2-11e9-9bb9-2def6cdf9e1f.png)

**Comment by updogliu** [comment]
@chenjiandongx I tried to produce the same chart in the example (see the picture in the first post) with `AddXAxis` and `AddYAxis` but failed. When adding [1, 2, 8, 9, 15] via `AddXAxis`, even with `Type: value`, they are still NOT shown at the right position of the value. Can you please take a try? Maybe this case (x coordinates of value type) worth adding as an example of Scatter.

**Comment by chenjiandongx** [comment]
@updogliu try this

```golang
scatter.
    AddXAxis([]string{"1", "2", "8", "9", "15"}).
    AddYAxis("name", []float64{5, 1, 2, 10, 20})
```

**Comment by updogliu** [comment]
@chenjiandongx I means treat the x coordinates as values (as opposed to texts of digits), which mean the distance between `1` and `2` is six times shorter than the distance between `2` and `8` (see the figure in the first comment).

Your snippet would show the x coordinates equidistantly. Setting `charts.XAxisOpts{Type: "value", Show: true}` would fix the positions of the x coordinates, but it would weirdly show the points on a straight-line:

![image](https://user-images.githubusercontent.com/1288299/61501642-b41d8200-aa02-11e9-8403-85687fd0f71b.png)

**Comment by chenjiandongx** [comment]
Got it, I seem to know where the problem is. I try to fix this issue tonight.Stay tune

**Comment by updogliu** [comment]
Come on... The last comment was `I try to fix this issue tonight. Stay tune`

**Comment by chenjiandongx** [comment]
There is no `AddYAxis` or `AddXAxis` function any longer  at v2
