### ISSUE TITLE
How to make a bar chart sorted？

### ISSUE THREAD

**Issue by ye-xiaowei** [go-echarts/go-echarts#301]
I want the pictures in the red box to be sorted
![image](https://github.com/go-echarts/go-echarts/assets/60205491/c4938414-e3d2-4ee0-bb6c-28bc2f2ed930)

**Comment by Koooooo-7** [comment]
Hi @ye-xiaowei , as per to this https://github.com/apache/echarts/issues/18271 ,  It seems there is no official api to do it either in normal bar chart or stack one.
