### ISSUE TITLE
toolbox `ToolBoxFeatureSaveAsImage.Type` has wrong json tag?

### ISSUE THREAD

**Issue by OutOfBedlam** [go-echarts/go-echarts#316]
The field `Type string` has a tag `json:"png,omitempty"`.
Should it be `json:"type,omitempty" default:"png"` instead?

Because of this, it always save the chart image as *.png.

https://github.com/go-echarts/go-echarts/blob/7f89eca5bd5707c4a23f2c9b9ab06bbe14d6b9bc/opts/global.go#L490

**Comment by Koooooo-7** [comment]
Hi @OutOfBedlam , thx for your report, I gonna have a fix on it asap.

**Comment by OutOfBedlam** [comment]
@Koooooo-7 thanks for your quick response. It works as expected!
