### ISSUE TITLE
`RectChart.Render` is not re-entrant

### ISSUE THREAD

**Issue by updogliu** [go-echarts/go-echarts#32]
`RectChart.Render` is not re-entrant, which means a chart variable `c` cannot be call with `c.Render(w)` more than once.

It would be nice if the `Render` function is reentrant. For example, when serving a chart via http, one could construct the chart for only once, and call `Render` on it in the http handler (instead of constructing the chart inside the http handler). Example code:
```go
s := charts.NewScatter()
// setup s ...
http.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) { s.Render(w) })
```
How difficult to make `Render` re-entrant?

**Comment by chenjiandongx** [comment]
Interesting issue. From the point of current condition, `Render` function will modify some chart options or attribute.

```go
func (c *Geo) Render(w ...io.Writer) error {
	c.insertSeriesColors(c.appendColor)
	c.validateOpts()
	return renderToWriter(c, "chart", []string{}, w...)
}
```

one of the solutions is setting some temporary vars to keep those attributes and reset them after render. Did you try that?

**Comment by Altenrion** [comment]
this method makes whole library weak =( 

Any wish of change in behaviour causes to fork and rewrite it.. Thinking exctly on that...
