### ISSUE TITLE
nameGap is missing

### ISSUE THREAD

**Issue by mitar** [go-echarts/go-echarts#323]
[nameGap](https://echarts.apache.org/en/option.html#xAxis.nameGap) option is not available on regular axis, but it looks like it should be.

**Comment by Koooooo-7** [comment]
Hi @mitar,  we support the most part of common options now. 
And we may add this `option` you mentioned later, and PR welcome.

**Comment by mitar** [comment]
I made PR: https://github.com/go-echarts/go-echarts/pull/324
