### ISSUE TITLE
User defined toolbox tools not supported?

### ISSUE THREAD

**Issue by mitar** [go-echarts/go-echarts#326]
[Echarts support used defined toolbox tools](https://echarts.apache.org/en/option.html#toolbox.feature) and go-echarts [comment says they are supported as well](https://github.com/go-echarts/go-echarts/blob/master/opts/global.go#L455), but I cannot find a way to define them. Are they?

**Comment by Koooooo-7** [comment]
Hi @mitar , We mainly support the configurable common useful opts of the toolbox (the same as other options), not a `flexible` structure. I don't think it is a lib thing that we provide just `interface{}` and you do the rest. 

I have to say go-echarts is part of the echarts implementations and it still needs more features and adaptions.
- Charts type.
- Charts Options.
- Charts (`echarts`) instance operation.
- Charts dynamic data/render.
- ...

If there is miss something, glad to hear your voice.
And I would appreciate that If you could do some contributions is a big plus.

**Comment by mitar** [comment]
OK, so if I understand, comment is currently wrong and this is not yet possible? But you are not opposed to adding such a feature and allow user defined tools?

**Comment by Koooooo-7** [comment]
> OK, so if I understand, comment is currently wrong and this is not yet possible? 

Yep, the comment sounds not align to current support options.

>  But you are not opposed to adding such a feature and allow user defined tools?  

Everyone knows the ideal things is `If it can do in echarts, it should do in go-echarts as well`.
The point is we need find a good way to implement it and make it easy to use. There needs lot of time to design and make it work, not just straightforward and crude change it to just make it work.

But we don't have a `Aladdin's magic lamp` to say I want it, then I have it. 

I don't have that much time to follow everyone's requirements and include the whole echarts' options/functions/features... asap. 

So, I do wanna more contributors who use go-echarts can share ideas and contribute something like the `allow user defined tools` , and benefit to others also.

**Comment by mitar** [comment]
> which means may need more of the JS context beyond go-echarts, even more ES modules...etc. The alert example in echarts is meaningless.

I do not think that is really necessary. In my case it is for example just to toggle some series to be shown or not. That is few lines of JavaScript.

**Comment by Koooooo-7** [comment]
> > which means may need more of the JS context beyond go-echarts, even more ES modules...etc. The alert example in echarts is meaningless.
> 
> I do not think that is really necessary. In my case it is for example just to toggle some series to be shown or not. That is few lines of JavaScript.

So, if we provide this features in the way of my assumption. It seems so much limitation to use it, and hard to use.
Or, you have any other thoughts on it?

**Comment by mitar** [comment]
I made https://github.com/go-echarts/go-echarts/pull/327. It works great for me. Allows me to add a simple tool to toggle series on and off in a batch.

**Comment by Koooooo-7** [comment]
> Allows me to add a simple tool to toggle series on and off in a batch.

What does it look like?

**Comment by mitar** [comment]
```js
function (){
	const chart = this.ecModel.scheduler.ecInstance;
	const series = [];
	for (const s of chart.getOption().series) {
		if (s.type === 'custom') {
			if (s.data.length === 0) {
				series.push({data: chart.getModel().getSeriesByName(s.name).filter((s) => s.subType === 'line')[0].option.data})
			} else {
				series.push({data: []});
			}
		} else {
			series.push({});
		}
	}
	chart.setOption({series: series});
}
```

It is a bit ugly because there is no simple way to toggle a series (https://github.com/apache/echarts/issues/15585), but it works. You can get `chart` instance from `this.ecModel.scheduler.ecInstance`. There are also other parameters passed as arguments to the click handler.

**Comment by Koooooo-7** [comment]
> It is a bit ugly because there is no simple way to toggle a series (https://github.com/apache/echarts/issues/15585), but it works. You can get chart instance from this.ecModel.scheduler.ecInstance. There are also other parameters passed as arguments to the click handler.

Thats cool.
