### ISSUE TITLE
拆线图x轴type:"value"问题

### ISSUE THREAD

**Issue by yangzj208** [go-echarts/go-echarts#33]
我想设置x轴为value类型，如下，出来的图各点的x,y值是一样的，给定的x轴没有起作用。请问这是怎么回事？谢谢
line := charts.NewLine()
	line.AddXAxis([]float32{1, 2, 5, 10, 15, 16, 17, 18}).
		AddYAxis("map", []float32{19.9, 16.8, 19.9, 29.4, 61.3, 77.3, 93.0, 10},
			charts.LabelTextOpts{Show: true, Position: "bottom"})
line.SetGlobalOptions(
		charts.TitleOpts{Title: "折线图示例"},
		charts.YAxisOpts{Name: "y(A)", SplitLine: charts.SplitLineOpts{Show: false}},
		charts.XAxisOpts{Name: "x(s)", Type: "value"})

![image](https://user-images.githubusercontent.com/29445634/62829866-d25b5400-bc35-11e9-999d-676e1cd49bf8.png)

如果改成charts.XAxisOpts{Name: "x(s)", Type: "category"}，如下图，这时x轴间隔是一样的，和标签值不致
![image](https://user-images.githubusercontent.com/29445634/62829886-4bf34200-bc36-11e9-8efd-4e44fc2bf040.png)

**Comment by chenjiandongx** [comment]
暂时的解决方案可以将 X 轴的 float 类型转换为 string 类型

**Comment by ch543ch543** [comment]
If this bug is solved? I'm facing the same problem now. Thanks!

**Comment by ch543ch543** [comment]
If the bug is solved? I'm facing the same issue as well. Thanks!

**Comment by yuyyi51** [comment]
> If the bug is solved? I'm facing the same issue as well. Thanks!

Seems when xAxis's type setting to 'value', yAxis's data should use points rather than only y-coordinate values. The code below runs good to me, maybe have a try.
```
func generateLineItems2() []opts.LineData {
	items := make([]opts.LineData, 0)
	for i := 0; i < itemCntLine; i++ {
		v := []interface{}{i,rand.Intn(300)}
		if i != 3 {
			items = append(items, opts.LineData{Value: v})
		}
	}
	return items
}

func lineBase() *charts.Line {
	line := charts.NewLine()
	line.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "basic line example", Subtitle: "This is the subtitle."}),
		charts.WithXAxisOpts(opts.XAxis{
			Type: "value",
		}),
		charts.WithYAxisOpts(opts.YAxis{
			Type: "value",
		}),
		charts.WithTooltipOpts(opts.Tooltip{
			Show: true,
			Trigger: "axis",
			AxisPointer: &opts.AxisPointer{
				Snap: true,
			},
		}),
	)

	line.AddSeries("Category A", generateLineItems2())
	return line
}
```
