### ISSUE TITLE
无法直接保存为png,或者其它格式的image文件

### ISSUE THREAD

**Issue by tsxylhs** [go-echarts/go-echarts#35]

**Comment by wlx10011101** [comment]
遇到同样问题，有法解吗？页面上能下载保存，代码里怎么保存呢？

**Comment by liyuanhang** [comment]
想保存成 jpg 或者 png，不知道怎么搞

**Comment by appleboy** [comment]
Any plan to save a screenshot?

**Comment by chenjiandongx** [comment]
因为 Echarts 是一个 js 项目，视图效果是通过浏览器渲染的。所以想要把 go-echarts 生成的图下载成 png/jpg 等图片格式的话必须要有一个浏览器的运行时。

类似 https://github.com/puppeteer/puppeteer 或者 https://phantomjs.org。原理就是把生产的 html 文件交由运行时渲染并且执行 js download 方法。

后面可以考虑提供一个插件来做这件事情，不过实际上这种渲染方式的效率还是比较低且耗费资源的。:)

**Comment by Hao-Wu** [comment]
实际上这个需求才是大家找到这个项目的原因。
否则直接在前端用echarts就好了。

**Comment by wr6412305** [comment]
这个需求就是使用GO在程序中根据数据生成定制化的图表,我觉得使用配置文件去解析生成图片才是正确的思路,基于JS生成这种前端直接获取数据完成

**Comment by andersling** [comment]
> 因为 Echarts 是一个 js 项目，视图效果是通过浏览器渲染的。所以想要把 go-echarts 生成的图下载成 png/jpg 等图片格式的话必须要有一个浏览器的运行时。
> 
> 类似 https://github.com/puppeteer/puppeteer 或者 https://phantomjs.org 原理就是把生成的 html 文件交由运行时渲染并且执行 js download 方法。
> 
> 后面可以考虑提供一个插件来做这件事情，不过实际上这种渲染方式的效率还是比较低且耗费资源的。:)

认同这位仁兄的观点:
你可以用chromedp来进行实现:


func save2PNG(file string) {
	// get full path of file
	abs, _ := filepath.Abs(file)

	// create context
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	// screenshot buffer
	var buf []byte

	// capture entire browser viewport, returning png with quality=100
	task := chromedp.Tasks{
		// use file:// for a local file
		chromedp.Navigate("file://" + abs + ".html"),
		// set resolution for screenshot
		chromedp.EmulateViewport(1200, 800),
		// take screenshot
		chromedp.FullScreenshot(&buf, 100),
	}

	// run tasks
	if err := chromedp.Run(ctx, task); err != nil {
		log.Fatal(err)
	}
	// write png
	if err := ioutil.WriteFile(abs+".png", buf, 0644); err != nil {
		log.Fatal(err)
	}
}

不过这个方法就会把生成的go执行程序暴增到15M以上,而且如果服务器很多请求的话,这个方式也可能有很大的内存和CPU压力.

**Comment by yqchilde** [comment]
如果可以RenderImage就好了

**Comment by chengfeiZhou** [comment]
echarts的渲染依赖dom, 不是能轻易解决的

**Comment by CatNum** [comment]
> 我先给各位搜索过来的探路了：推荐一个在go后端生成可视化图表的图片文件的项目 https://github.com/gonum/plot
> 
> 已经用在我得项目中。虽然视觉效果不如echarts这类前端图表，但是生成图片以及数据处理也还算比较方便，达到生产使用程度了。
> 
> ![image](https://user-images.githubusercontent.com/860738/185478417-f12536fb-36cf-4964-8117-93e9bfd96a81.png)

这个不能生成饼图吧

**Comment by Hao-Wu** [comment]
> > 我先给各位搜索过来的探路了：推荐一个在go后端生成可视化图表的图片文件的项目 https://github.com/gonum/plot
> > 已经用在我得项目中。虽然视觉效果不如echarts这类前端图表，但是生成图片以及数据处理也还算比较方便，达到生产使用程度了。
> > ![image](https://user-images.githubusercontent.com/860738/185478417-f12536fb-36cf-4964-8117-93e9bfd96a81.png)
> 
> 这个不能生成饼图吧

有第三方社区实现
https://github.com/benoitmasson/plotters/tree/master/piechart

**Comment by Koooooo-7** [comment]
It has been implemented in [snapshot-chromedp](https://github.com/go-echarts/snapshot-chromedp), plz have a try on it.
And thanks to @andersling  who raised this lib out. 👍
