### ISSUE TITLE
Unable to pass renderer option to the template through page options

### ISSUE THREAD

**Issue by mitar** [go-echarts/go-echarts#355]
I have code like:

```go
	page := components.NewPage()
	page.SetLayout(components.PageFlexLayout)
	page.PageTitle = "report"
	page.AssetsHost = p.Assets

	for config, allMeasurements := range data {
		for _, name := range []string{"foo", "bar"} {
			plot := p.renderPlot(config, name, allMeasurements)
			page.AddCharts(plot)
		}
	}

	f, err := os.Create(p.Output)
	if err != nil {
		return errors.WithStack(err)
	}
	defer f.Close()

	return page.Render(f)
```

And this works (it sets the title of the page, for example).

But if I add:

```go
page.Initialization.Renderer = "svg"
```

Then it does not render charts with "svg" renderer. I think the issue is that options from the page are not inherited by the charts renderer?

**Comment by Koooooo-7** [comment]
> Then it does not render charts with "svg" renderer. I think the issue is that options from the page are not inherited by the charts renderer?

Yes, the charts and the page is totally separated configs now.
We only do the JS and CSS assets merge stuff between page level and charts level. no inherited mechanism.
The `page` only hold the whole HTML page level configs,  it doesn't be treated as the default global configs for each charts.
It may need enhancement.

**Comment by mitar** [comment]
Maybe it is fine, it is just confusing because you are able to set `page.Initialization.Renderer`. Maybe page and charts should not share the same set of options.
