### ISSUE TITLE
how to modify MarkLine color

### ISSUE THREAD

**Issue by burgess001** [go-echarts/go-echarts#365]
how to modify MarkLine color,like this

<img width="1377" alt="image" src="https://github.com/go-echarts/go-echarts/assets/22974847/f35d601f-4da2-4cf3-b749-a5c8dfb500fc">

**Comment by Koooooo-7** [comment]
Hi @burgess001 , currently we don't have a `WithHelper` to change this easily.
Luckily I checked the `series` configs, it contains the `MarkLine` configs in `interface{}`.
You can do this as a workaround.
```go

type MyItem struct {
	Name           string `json:"name"`
	YAxia          int    `json:"yAxia"`
	opts.LineStyle `json:"lineStyle"`
}

func barMarkLines() *charts.Bar {
	bar := charts.NewBar()
	bar.SetSeriesOptions(charts.WithSeriesOpts(func(s *charts.SingleSeries) {
		s.MarkLines = &opts.MarkLines{}
		s.MarkLines.Data = append(s.MarkLines.Data, &MyItem{
			Name:  "1111",
			YAxia: 200,
			LineStyle: opts.LineStyle{
				Color: "red",
			},
		})

	}))
	return bar
}

```
