### ISSUE TITLE
生成的html文件找不到加载的js文件

### ISSUE THREAD

**Issue by kunshao753** [go-echarts/go-echarts#37]
生成html文件后，发现打开页面没有显示任何内容。访问head标签里引用的js文件：http://chenjiandongx.com/go-echarts-assets/assets/echarts.min.js 出现404

**Comment by chenjiandongx** [comment]
更新一下 go-echarts。现在项目已经转移至 go-echarts 组织下。

**Comment by kunshao753** [comment]
> 更新一下 go-echarts。现在项目已经转移至 go-echarts 组织下。

可以了，谢谢大佬及时回复
