### ISSUE TITLE
Is there a way to download an image directly as png or jpg?

### ISSUE THREAD

**Issue by vcabales** [go-echarts/go-echarts#38]
I know this is possible in the JavaScript library in echartsInstance.getDataURL. Is there a similar feature here?

**Comment by thenick775** [comment]
I used this the other day and everything worked as expected:
https://pkg.go.dev/github.com/go-echarts/go-echarts/v2@v2.0.0/opts#ToolBoxFeatureSaveAsImage

**Comment by m4r3x** [comment]
From my initial research, as I understand, there is no option to programmatically use different io.Writer than `.html`file. The ToolBoxFeatureSaveAsImage just adds the Toolbox which can be later used to download an image, but actual rendering must be done within the browser.

So the only possibility to achieve this is to use some sort of headless browser that will enter generated page and initiate the download :(

Unless I am mistaken and there's an option to do that easier?

**Comment by m4r3x** [comment]
From my initial research, as I understand, there is no option to programmatically use different io.Writer than `.html` file. The [ToolBoxFeatureSaveAsImage](https://pkg.go.dev/github.com/go-echarts/go-echarts/v2@v2.0.0/opts#ToolBoxFeatureSaveAsImage) just adds the Toolbox which can be later used to download an image, but actual rendering must be done within the browser.

So the only possibility to achieve this is to use some sort of headless browser that will enter generated page and initiate the download :(

Unless I am mistaken and there's an option to do that easier?

**Comment by m4r3x** [comment]
From my initial research, as I understand, there is no option to programmatically use different io.Writer than `.html` file. The [ToolBoxFeatureSaveAsImage](https://pkg.go.dev/github.com/go-echarts/go-echarts/v2@v2.0.0/opts#ToolBoxFeatureSaveAsImage) just adds the Toolbox which can be later used to download an image, but actual rendering must be done within the browser.

So the only possibility to achieve this is to use some sort of headless browser that will enter generated page and initiate the download :(

Unless I am mistaken and there's an option to do that easier?

**Comment by m4r3x** [comment]
From my initial research, as I understand, there is no option to programmatically use different io.Writer than `.html` file. The [ToolBoxFeatureSaveAsImage](https://pkg.go.dev/github.com/go-echarts/go-echarts/v2@v2.0.0/opts#ToolBoxFeatureSaveAsImage) just adds the Toolbox which can be later used to download an image, but actual rendering must be done within the browser.

So the only possibility to achieve this is to:
- use headless browser that will enter generated page and initiate the download :(
- wkhtmltoimage (or similar package)
- use external APIs that do html -> img as a service

Unless I am mistaken and there's an option to do that easier?

**Comment by iyashjayesh** [comment]
> I used this the other day and everything worked as expected: https://pkg.go.dev/github.com/go-echarts/go-echarts/v2@v2.0.0/opts#ToolBoxFeatureSaveAsImage

any example would be a great help.

**Comment by dickyjoelsaputra** [comment]
have this problem as well

**Comment by N1nj4-1kt4** [comment]
This library is a wrapper over Apace eCharts - an open-source Javascript framework for charting.

Apache eCharts provides an option to programmatically download the image
https://echarts.apache.org/en/api.html#echartsInstance.getDataURL

If the Go library can expose that Javascript endpoint, then can easily save the chart as an image.

**Comment by N1nj4-1kt4** [comment]
Here are the steps to do this without needing a headless browser to clock the "Save as Image" button.

Core knowledge: The rendered HTML page has "goechart_XXXXX" format Javascript object. On this object, one can call the getDataURL method to get a Base64 version of the PNG equivalent of the chart.

Step 1. Load the generated HTML page using ioUtil.ReadFile

Step 2. Do a regex inside the HTML page to find Javascript object variable matching "goechart_<some string>"

Step 3. Load the HTML file into a Javascript engine. Can use "github.com/rogchap/v8go" for this

Step 4. Use the Javascript engine to execute getDataURL method on the desired "goechart_<some string> object

Step 5. Decode the result string using "base64" package from Go's standard library and write out the decoded binary data into a file with ".png" extension
