### ISSUE TITLE
[Bug] 数据量较大时Scatter3D组件的标签显示乱码

### ISSUE THREAD

**Issue by lwch** [go-echarts/go-echarts#403]
### Describe the issue

![image](https://github.com/go-echarts/go-echarts/assets/4181963/0e7e2e2f-d1cd-427c-927d-ea361628f61d)

代码如下：

```go
page := charts.NewScatter3D()
page.Initialization.Width = "100%"
page.Initialization.Height = "700px"
page.SetGlobalOptions(
charts.WithTitleOpts(opts.Title{Title: "embedding"}),
charts.WithTooltipOpts(opts.Tooltip{Show: true, Trigger: "item"}),
charts.WithVisualMapOpts(opts.VisualMap{
	Calculable: true,
	Max:        max,
	Min:        min,
	InRange:    &opts.VisualMapInRange{Color: colors},
}),
charts.WithLegendOpts(opts.Legend{Show: false}),
)
page.AddSeries("embedding", values)
```

添加数据时设置了label属性：

```go
pt := opts.Chart3DData{
	Name: tokens[i/3],
	Value: []interface{}{
		data[i], data[i+1], data[i+2],
	},
	Label: &opts.Label{
		Show:      true,
		Formatter: "{b}",
	},
}
```

### How to reproduce this issue

需要随机生成一些数据，不论怎么转动也无法正常显示

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @lwch ,  应该是`echarts` 在处理大数据的时候，有些问题。
我看到这个issue https://github.com/apache/echarts/issues/14033 , 类似于scatter的配置`large` 参数目前3D还不支持。
......估计目前只能考虑减少一下向量data了。

**Comment by lwch** [comment]
> Hi @lwch , 应该是`echarts` 在处理大数据的时候，有些问题。 我看到这个issue [apache/echarts#14033](https://github.com/apache/echarts/issues/14033) , 类似于scatter的配置`large` 参数目前3D还不支持。 ......估计目前只能考虑减少一下向量data了。

我尝试了另外几台机器，苹果M2和AMD显卡台式机都没有出现问题，但在AMD集显的笔记本上出现了上面的问题，可能是AMD集显的渲染方式问题

**Comment by Koooooo-7** [comment]
> > Hi @lwch , 应该是`echarts` 在处理大数据的时候，有些问题。 我看到这个issue [apache/echarts#14033](https://github.com/apache/echarts/issues/14033) , 类似于scatter的配置`large` 参数目前3D还不支持。 ......估计目前只能考虑减少一下向量data了。
> 
> 我尝试了另外几台机器，苹果M2和AMD显卡台式机都没有出现问题，但在AMD集显的笔记本上出现了上面的问题，可能是AMD集显的渲染方式问题

Nice catch!
这个可能要promote到echarts那边去看看了。（ btw: `AMD, yes!` xD
