### ISSUE TITLE
charts.Map 问题询问

### ISSUE THREAD

**Issue by kingsley8524267** [go-echarts/go-echarts#408]
### Describe your question

问题1：如何让point1在地图上的”蓝点“消失
![image](https://github.com/go-echarts/go-echarts/assets/133184499/1d983be8-4c9e-42ee-8cca-7ff688c5c056)

问题2：如何让当point2打开时会显示point1的颜色，不显示白色，相当于point1的地图填色相当于地图的基色
![image](https://github.com/go-echarts/go-echarts/assets/133184499/29fbeba6-8c65-497a-8fd3-11f1db11df51)

期望做出类似这样的效果(地图上红色的雷相当于是Point 2)：
![image](https://github.com/go-echarts/go-echarts/assets/133184499/6a7a1a54-506b-41ae-8b29-1c12173012cb)

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @kingsley8524267 , go-echarts 目前还不能很好支持这样的自定义化的图配置，可以先看看echarts怎么用可以达到这个效果，然后把对应的options配置转到go-echarts里。
