### ISSUE TITLE
YAxis has no minInterval 

### ISSUE THREAD

**Issue by flower-ro** [go-echarts/go-echarts#411]
### Describe your question

my YAxis data is decimal as below,but i want YAxis data is integer and mininterval should be 1 ,go-echarts repo YAxis attribute
has no mininterval although  XAxis attribute has mininterval 
![image](https://github.com/go-echarts/go-echarts/assets/30053583/be8f1334-dd17-469a-b0e1-40f5a83306ac)

![image](https://github.com/go-echarts/go-echarts/assets/30053583/62322ed6-3278-445c-82a4-19d18c7af9cc)

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @flower-ro , thx for ur report.
It seems go-echarts misses the options in y axis, it will be added in next release, thx.
