### ISSUE TITLE
Polar plots failing with `undefined findAxisModel`

### ISSUE THREAD

**Issue by janpfeifer** [go-echarts/go-echarts#414]
### Describe the issue

hi,

I'm trying to reproduce some of the demos in [Apache ECharts](https://echarts.apache.org/examples/en/index.html), and in the [Two Values-Axes in Polar](https://echarts.apache.org/examples/en/editor.html?c=line-polar) I'm doing the following:

```go
const numPoints = 100
data := make([]opts.LineData, numPoints)
for ii := range 100 {
    theta := (float64(ii) / numPoints) * 360.0;
    r := 5 * (1.0 + math.Sin((theta / 180) * math.Pi));
    data[ii] = opts.LineData{Value: []float64{r, theta}}
}

polar := charts.NewLine()
polar.SetGlobalOptions(
    charts.WithTitleOpts(opts.Title{Title: "Two Value-Axes in Polar",}), 
    charts.WithPolarOps(opts.Polar{
        Tooltip: opts.Tooltip{
            Show: true,
            Trigger: "axis",
            AxisPointer: &opts.AxisPointer{Type: "cross"},
        },
    }),
    charts.WithAngleAxisOps(opts.AngleAxis{
        PolarAxisBase: opts.PolarAxisBase{
            Type: "value",
            StartAngle: 0.0,
        },
    }),
    charts.WithRadiusAxisOps(opts.RadiusAxis{}),
)
polar.AddSeries(
    "line", data, charts.WithCoordinateSystem("polar"))
```

Which looks correct, but when I plot it, I get the following Javascript error in the console:

```
echarts.min.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'findAxisModel')
    at polar (echarts.min.js:45:242322)
    at echarts.min.js:45:244427
    at vx (echarts.min.js:45:244464)
    at e.getInitialData (echarts.min.js:45:324278)
    at e.init (echarts.min.js:45:158856)
    at e.<anonymous> (echarts.min.js:45:113807)
    at Array.forEach (<anonymous>)
    at E (echarts.min.js:35:5056)
    at e.<anonymous> (echarts.min.js:45:113440)
    at t.topologicalTravel (echarts.min.js:45:106659)
```

Maybe I'm doing something wrong ? Any ideas ? 

Thanks!!

### How to reproduce this issue

Just use the code in description.

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @janpfeifer , I reproduced the issue and checked the options, it generated wrong `polar` related options here.
go-echarts seems has a weird process on the `Polar` config now.
I gonna take a look on it and have a fix.

**Comment by janpfeifer** [comment]
Thank you! I'm in a trip, so I haven't had the chance to check, but very appreciated!!

**Comment by Koooooo-7** [comment]
> Thank you! I'm in a trip, so I haven't had the chance to check, but very appreciated!!

No prob.
Although I fix this, I haven't released it yet. :)
Have a nice day.
