### ISSUE TITLE
前端代码是否耦合度太高

### ISSUE THREAD

**Issue by lvyishan** [go-echarts/go-echarts#42]
您好:
现在是基于golang 的echarts类型将结果直接write成html file ，能否新增其他的output 类型，例如：svg image 甚至struct数据结构（交由js自行load）
期待您的更新

**Comment by chenjiandongx** [comment]
pyecharts 就有提供相关的插件，但是目前 go-echarts 还没有。

主要是利用 phantomjs/selenium/.. 等无头浏览器接口实现。如果你感兴趣的话可以研究一下，目前没有开发这个功能的打算。
