### ISSUE TITLE
Using go-echart...focus on responsiveness

### ISSUE THREAD

**Issue by tobigiwa** [go-echarts/go-echarts#426]
### Describe your question

Please show me how to use the package, especially marking the chart responsive.
https://github.com/tobigiwa/help
I have tried to cut-out peices of the code from the whole project. Thanks in advance.

Comment on the repo above on here would be fine.

### Code pieces of your question

....

### go-echarts version

2.3.4

**Comment by Koooooo-7** [comment]
Hi @tobigiwa , sorry for the delay and I do get your email also. :)

IIUC, you wanna make the charts can dynamic update as per to the backend data flushing.
I checked the codebase you provided, it seems that you didn't reload the echarts instance with `setOption`.
see [data transition](https://echarts.apache.org/handbook/en/how-to/animation/transition)

You can simply add the JS snippets in your custom template.
```
setInterval(() => {
  myChart.setOption({
    series: {
      data: // call API to get new data
    }
  });
}, 2000);
```

**Comment by tobigiwa** [comment]
@Koooooo-7 pardon for jamming into your mail, I was just out of options. Firstly, let me drawn your attention to this:

*** if you noticed the pie chart, it has some other plumbing to render the chart ONLY, unlike the the default go-echart that renders a whole HTML. With the advent of templ and htmx, it would be nice if this plumbing is built-in to the library... I swear to God, it is useful.

so here are my problem:
1) going with the plumbing, i cannot make the chart to take up the available space i'm giving to it, the whole of the id=#echart

2) when window resizes, the chart does not respond to this change...the whole thing overflow, gives a horizontal scrollbar.

I think does are my problem... believe me, my first choice was go-echart, when i could not make it work, i had to go back to chartjs...but it breaking the htmx principle of using hypermedia as a response...that is why am back here.


@Koooooo-7 regarding your response, i cannot make much sense of it,

```go
func createBarChart() *charts.Bar {
	const actionsWithEchartInstance = `
 const myChart = %MY_ECHARTS%;
 window.onresize = function ()
     {
         myChart.resize();
     };`
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "title and legend options",
			Subtitle: "go-echarts is an awesome chart library written in Golang",
			Link:     "https://github.com/go-echarts/go-echarts",
			Right:    "40%",
		}),
		charts.WithLegendOpts(opts.Legend{Right: "80%"}),
	)
	weeks := []string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}

	// bar.AddJSFuncs(opts.FuncOpts(actionsWithEchartInstance))
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	return bar
}
```
am i supposed to add it to that "actionsWithEchartInstance" string, cause anytime i used that, the chart just goes blank

**Comment by tobigiwa** [comment]
I've left a detailed explanation on Github... I very much appreciate the
attention. God bless you and your work.

**Comment by tobigiwa** [comment]
@Koooooo-7 Please don't curse me for endlessly calling on you...am sorry. I have been able to fix the first problem, the chart taking the space given to it...the issue was with templ not generating an updated template. i have fixed that my removing all the templ first in the makefile, so, if you'll be running the code, please use the **make run** command.

The second problem is the chart resizing with the window, unsolved.

**Comment by tobigiwa** [comment]
If I'm being rude in anyway... please pardon me, it was not intentional. Thank you for your time.

**Comment by Koooooo-7** [comment]
Hi @tobigiwa , could you plz tell me how to reproduce the issue ?
> when window resizes, the chart does not respond to this change...the whole thing overflow, gives a horizontal scrollbar.

I don't see a scrollbar here although I make the window much smaller.
![Screenshot 2024-05-16 at 22 56 15](https://github.com/go-echarts/go-echarts/assets/33706142/7e4ce69b-18c9-4507-82d6-7f0df37d2545)

**Comment by tobigiwa** [comment]
That there is exactly the problem....I thought the chart was to be confined in that red-like color.
Yunno... get smaller in width has the window size decreases.

**Comment by Koooooo-7** [comment]
> That there is exactly the problem....I thought the chart was to be confined in that red-like color. Yunno... get smaller in width has the window size decreases.

I see, I think it needs the `resize` call to do the trick that resize the chart container immediately. 
Plz add this code in the `baseTpl` and try again.
```
 window.addEventListener('resize', function() {
    goecharts_{{ .ChartID | safeJS }}.resize();
  });
```
![Screenshot 2024-05-16 at 23 13 42](https://github.com/go-echarts/go-echarts/assets/33706142/56d6746c-1690-4194-a183-aa2b0868b51a)

**Comment by tobigiwa** [comment]
Thank you @Koooooo-7 , the solution works perfectly,  buh i'll like to draw your attention to something else
![Screenshot from 2024-05-16 17-03-50](https://github.com/go-echarts/go-echarts/assets/73890077/aa1256cb-44a3-4f25-957a-c0fba5af1dc5)

How can i bundle this into my code locally...cos anyhing my system is not connected to the internet, it just black page.

**Comment by Koooooo-7** [comment]
> How can i bundle this into my code locally...cos anyhing my system is not connected to the internet, it just black page.

You can simply change the resources to locally resources.
- download the `echarts.min.js` locally.
- set the resources host as what you want. i.e. the `/my/localhost/assets/`, it will retrieve the resource as `/my/localhost/assets/echarts.min.js`
  ```go
        pie := charts.NewPie()
        pie.SetGlobalOptions(
		charts.WithInitializationOpts(
			opts.Initialization{AssetsHost: "/my/localhost/assets/"},
		)
	
  ```

**Comment by tobigiwa** [comment]
Thank you very much... I'll try this and get back to you... I'm away from my pc at the moment. Again, thank you very much for the time.

**Comment by tobigiwa** [comment]
I have tried the solution... it works perfectly, thanks again.
