### ISSUE TITLE
Tooltip and Y axis label

### ISSUE THREAD

**Issue by tobigiwa** [go-echarts/go-echarts#427]
### Describe your question

1) Can't figure to set label on the y-axis, like the unit of the values.

2) can I set a url in each bar?, such that a click on it fires am AJAX request.

Thanks

### Code pieces of your question

```go

func weekStatBarChart(data barChartData) template.HTML {
	bar := charts.NewBar()

	bar.SetGlobalOptions(charts.WithInitializationOpts(
		opts.Initialization{AssetsHost: "/assets/"},
	))
	bar.Renderer = newchartRenderer(bar, bar.Validate)

	hrs, min := hrsAndMinute(data.totalUptime)

	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Weekly Screentime",
			TitleStyle: &opts.TextStyle{
				Color:      "black",
				FontStyle:  "bold",
				FontSize:   100,
				FontFamily: "system-ui",
			},
			Subtitle: fmt.Sprintf("from %s - %s %s. Total Uptime of %dHr:%dMin", data.xAxis[0], data.xAxis[6], data.month, hrs, min),
			SubtitleStyle: &opts.TextStyle{
				Color:      "black",
				FontStyle:  "bold",
				FontSize:   13,
				FontFamily: "system-ui",
			},
			Left: "center",
		}),
		charts.WithLegendOpts(opts.Legend{Right: "80%"}),
	)
	bar.SetXAxis(data.xAxis).
		AddSeries("Daily Uptime", generateBarItems(data.yAxis))
	return renderToHtml(bar)
}



func generateBarItems(yAxis [7]float64) []opts.BarData {
	items := make([]opts.BarData, 0, 7)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{
			Name:  "fine",
			Value: yAxis[i],
			Tooltip: &opts.Tooltip{
				Show:        true,
				Trigger:     "axis",
				TriggerOn:   "mousemove",
				AxisPointer: &opts.AxisPointer{},
			},

			Label: &opts.Label{
				Color:     "auto",
				FontStyle: "bold",
			},
			ItemStyle: &opts.ItemStyle{
				Color:       barColors[i],
				BorderColor: barColorsBackGround[i],
			}})
	}
	return items
}
```

### go-echarts version

1.22.1

**Comment by Koooooo-7** [comment]
Hi @tobigiwa 
> 1. Can't figure to set label on the y-axis, like the unit of the values.

Not quite understand the behavior, could you provide a sample pic or more details?

> 2. can I set a url in each bar?, such that a click on it fires am AJAX request.

On options level, no readily available config to use for now,  it suppose out of chart scope.

To achieve this, I think you may try to use the `Event and Action` instead（ensure your go-echarts version is `v2.4.0-rc1`）:
1. Listen the click event for each bar series data.
2. Open the corresponding urls.

more details：
[echart-doc](https://echarts.apache.org/handbook/en/concepts/event)
[go-echarts-interface](https://go-echarts.github.io/go-echarts/#/en-us/event-and-action)

**Comment by Koooooo-7** [comment]
Hi @tobigiwa , IMHO, styling things is much over the data visualization scope of go-echart. 
I suppose you should only use go-echarts to generate the basic chart you want , and styling it in the generated resources directly.
Alternatively, if you wanna build a nice data visualization with nice web UX and lots of custom `front end` things, plz use echarts directly. It is more feasible and reasonable.

**Comment by tobigiwa** [comment]
The problem is am using htmx for the frontend, so I have to package all my stuff from the backend. I was using chartjs initially, buh the idea of sending Json with htmx wasn't just pleasing.
Is it possible to use the addJsFunc for the styling, would that still work?

**Comment by Koooooo-7** [comment]
> The problem is am using htmx for the frontend, so I have to package all my stuff from the backend. I was using chartjs initially, buh the idea of sending Json with htmx wasn't just pleasing. Is it possible to use the addJsFunc for the styling, would that still work?

Technically, you can get the `echarts` instance `%MY_ECHARTS`, so you can do everything you want for the echarts instance. As long as it is feasible in echarts, you can achieve it via `addJsFunc` or customizing your own template and write the pure JS/CSS directly.

**Comment by tobigiwa** [comment]
Then the library is as powerful as needed,thank you so much @Koooooo-7 , I very much appreciate this. I don't think I've had such help from library/framework authors like this before.

I suppose I should create another issue for any other questions, right? since you closed this. 
Also, I noticed go-echart is not on the Go official slack channel, it would be nice to have it there too.

**Comment by Koooooo-7** [comment]
> Then the library is as powerful as needed,thank you so much @Koooooo-7 , I very much appreciate this. I don't think I've had such help from library/framework authors like this before. I will try the JsFunc option, would give feedback/question.

No prob.


> I suppose I should create another issue for any other questions, right? since you closed this. Also, I noticed go-echart is not on the Go official slack channel, it would be nice to have it there too.

Yes, one issue for one single topic is more clear to work on.

I'm not quite jump into some social stuff, I may take a look on it.
