### ISSUE TITLE
How to get e-chart compatitable Options as JSON from chart object ?

### ISSUE THREAD

**Issue by Altenrion** [go-echarts/go-echarts#43]
As I understood from exploring china docs (khe, khe....), the are possibilities to render your chart to the predefined templates. 

In my project I need to get only JSON data that represents whole chart and save it as string. 

I understands that i can rewrite templates, but with current architecture I would need to refactor whole library or write my own. 

Is it possible to get JSON chart representation or not?

**Comment by seanrmurphy** [comment]
I was looking for similar functionality and have done some work in this direction - did you manage to find a solution?

**Comment by seanrmurphy** [comment]
I've written a partial solution in this branch:

https://github.com/seanrmurphy/go-echarts/tree/feature/add_js_option_mapping

It does not have full coverage of all chart types and some options are not yet supported.

The usage is something like the following:

```
c := charts.NewLine()
c.AddXAxis(nameItems).AddYAxis("Series A", randInt())

// new function - returns a set of options for the chart
// in a JS compatible Go object
o := c.GenerateOptions()

// call JS echarts functionality
echarts := js.Global().Get("echarts")
div := js.Global().Get("document").Call("querySelector", "#"+ID)
chart := echarts.Call("init", div, "white")
chart.Call("setOption", js.ValueOf(o))

```

Of course, it assumes it is working inside a page with the correct setup (the div exists, there is sensible CSS and this functionality is called when the div is being rendered).

If there is interest in merging this, I could prob do some work in that direction; for now, the point was to see how it could work (I'll also publish a post on it and add the link here).

**Comment by chenjiandongx** [comment]
Hi @Altenrion @saromanov 

I'm refactoring the go-echarts project recently and the next version of it has more interesting features. I think we can find a channel where we can communicate together.

Like telegram?

**Comment by seanrmurphy** [comment]
I can help out on this issue to some extent.

**Comment by chenjiandongx** [comment]
@seanrmurphy great job.

This feature will be supported at the next version v2 :)

**Comment by seanrmurphy** [comment]
@chenjiandongx - if I can help out, let me know...

**Comment by chenjiandongx** [comment]
@seanrmurphy @Altenrion v2 adds a `JSON()` fucntion for every charts https://github.com/go-echarts/go-echarts/pull/127
