### ISSUE TITLE
Formatting go-echart tooltip value

### ISSUE THREAD

**Issue by tobigiwa** [go-echarts/go-echarts#431]
### Describe your question

![Screenshot from 2024-05-26 19-22-41](https://github.com/go-echarts/go-echarts/assets/73890077/f42073f1-a53b-4b43-a90e-1e7e0ad628d0)
I want to format the value that is displayed by the tooltip, I can't seem to get the valueFormatter field to. Please what am i doing wrong?

### Code pieces of your question

```go

func WeekStatBarChart(data BarChartData) template.HTML {
	bar := charts.NewBar()

	bar.SetGlobalOptions(charts.WithInitializationOpts(
		opts.Initialization{AssetsHost: "/assets/"},
	))
	bar.Renderer = newchartRenderer(bar, bar.Validate)

	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Weekly Screentime",
			TitleStyle: &opts.TextStyle{
				Color:      "black",
				FontStyle:  "bold",
				FontSize:   100,
				FontFamily: "system-ui",
			},
			Subtitle: fmt.Sprintf("from %s - %s %s. Total Uptime of %s", data.XAxis[0], data.XAxis[6], data.Month, helperFuncs.UsageTimeInHrsMin(data.TotalUptime)),
			SubtitleStyle: &opts.TextStyle{
				Color:      "black",
				FontStyle:  "bold",
				FontSize:   13,
				FontFamily: "system-ui",
			},
			Left: "center",
		}),
		charts.WithYAxisOpts(opts.YAxis{
			Name:         "in Hours",
			Type:         "value",
			NameLocation: "end",
			NameGap:      5,
			Scale:        true,
		}),
		charts.WithLegendOpts(opts.Legend{
			Left:   "left",
			Orient: "vertical",
		}),
		charts.WithTooltipOpts(opts.Tooltip{
			Show:      true,
			Trigger:   "axis",
			TriggerOn: "mousemove",
			AxisPointer: &opts.AxisPointer{
				Type: "cross",
			},
			Formatter: fmt.Sprintf("{b} %s, %s. <br/> {a}: {c}Hrs", data.Month, data.Year),
			// ValueFormatter: "0.2f",
			// ValueFormatter: TooltipFormatterJSFunc,
		}),
	)
	bar.SetXAxis(data.XAxis).
		AddSeries("Uptime", generateBarItems(data.YAxis, data.XAxis)).SetSeriesOptions()
	return renderToHtml(bar)
}

func generateBarItems(YAxis []float64, xAxis []string) []opts.BarData {
	items := make([]opts.BarData, 0, 7)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{
			Name:  xAxis[i],
			Value: YAxis[i],
			Label: &opts.Label{
				Color:     "auto",
				FontStyle: "bold",
			},
			ItemStyle: &opts.ItemStyle{
				Color:       barChartColors[i],
				BorderColor: barChartColorsBackGround[i],
			},
			Tooltip: &opts.Tooltip{},
		})
	}
	return items
}

const TooltipFormatterJSFunc = `function (params) {
    var hours = Math.floor(params.value);
    var minutes = Math.round((params.value - hours) * 60);
    return hours + 'hrs:' + minutes + 'min';
}`
```

### go-echarts version

latest

**Comment by Koooooo-7** [comment]
Hi @tobigiwa , `Formatter ` is literally a formatter string, I'm not quite sure what the `data.Month` and `data.Year` is.
FYI. [Tooltip formatter](https://echarts.apache.org/en/option.html#tooltip.formatter)

**Comment by tobigiwa** [comment]
Thanks for the reply @Koooooo-7 , I get  the part of the string formatter, but what I'm asking is how to insert the "Pure Js Func" as said in the docs.
![Screenshot from 2024-05-28 06-43-39](https://github.com/go-echarts/go-echarts/assets/73890077/c5599d17-3b9d-4243-901d-3bfae517166b)
This below are thinks I have tried;
![45678](https://github.com/go-echarts/go-echarts/assets/73890077/a5e8ff5d-5885-4734-964e-16a6b50cd01d)
![123](https://github.com/go-echarts/go-echarts/assets/73890077/2c8b726c-deb8-4177-82bc-ff07b6817424)
And for any of these options that involves the js string, this is what I get
![Screenshot from 2024-05-28 06-49-29](https://github.com/go-echarts/go-echarts/assets/73890077/9c693051-b861-4aa1-b77c-3c0bb272ee9a)

my go-echart version is v2.3.3

**Comment by Koooooo-7** [comment]
I see. How to insert JS func you can refer to the [treemap example](https://github.com/go-echarts/examples/blob/953630053c29e20c292ed38f3582daaab09bd13e/examples/treemap.go#L64).

**Comment by tobigiwa** [comment]
> I see. How to insert JS func you can refer to the [treemap example](https://github.com/go-echarts/examples/blob/953630053c29e20c292ed38f3582daaab09bd13e/examples/treemap.go#L64).

Works perfectly fine.
