### ISSUE TITLE
[Question] undefined: opts.Bool. Cannot compile due to undefined: opts.Bool

### ISSUE THREAD

**Issue by flaneur7508** [go-echarts/go-echarts#435]
### Describe your question

I'm importing:

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"

But when I compile I get the error: ./chartrevenue.go:475:20: undefined: opts.Bool

### Code pieces of your question

```
bar.SetXAxis(startMthNames).
		//AddSeries("Revenue", barDataRevenue).
		AddSeries("Revenue", barDataRevenue, charts.WithMarkPointNameCoordItemOpts(opts.MarkPointNameCoordItem{
			Name:       "special mark",
			Coordinate: []interface{}{"Mon", 100},
			Label: &opts.Label{
				Show:     opts.Bool(true),
				Color:    "pink",
				Position: "inside",
			},
		})).
		AddSeries("Visits", barDataVisits)
```

### go-echarts version

Latest

**Comment by tobigiwa** [comment]
I bet you're using v2.3.3 ... I think you need  v2.4.0-rc1 and greater... but with v2.3.3, the option type is bool, so passing in "true" is fine.

**Comment by flaneur7508** [comment]
Thank you. You are correct. My go.mod was pointing to the wrong version.
