### ISSUE TITLE
[Question] How to render body only?

### ISSUE THREAD

**Issue by nexovec** [go-echarts/go-echarts#437]
### Describe your question

Hi, when using the `.Render()` methods, it generates an entire page with a doctype, headers and so on.
Is there a way to render just the html for the graph?

### go-echarts version

I'll use any version you can solve this for.

**Comment by marcelhfm** [comment]
I don't know if this will help you, but you could Render into a buffer and then manipulate the string manually.

```go
var buf bytes.Buffer
err := lineChart.Render(&buf)
```

**Comment by tobigiwa** [comment]
Or try using the pre-release version, v2.4.0-rc1/r2, it has a snippet render... I could not figure it out though. Interest in my own workaround?

**Comment by Koooooo-7** [comment]
Hi @nexovec , plz try the latest version `v2.4.0-rc2` and use the `snippets`.
Refer [endersnippet-chartsnippet](https://go-echarts.github.io/go-echarts/#/en-us/render?id=rendersnippet-chartsnippet).
