### ISSUE TITLE
[Question] learning Go and Go-Echarts. Question concerning the gauge

### ISSUE THREAD

**Issue by flaneur7508** [go-echarts/go-echarts#438]
### Describe your question

Hello, i'd like to define the minimum and maximum value for a gauge but I cannot see any Min/Max fields in opts relating to the gauge. 
If anyone can advise how i can do this i'd appreciate it!
Thank you

### go-echarts version

 v2.4.0-rc2

**Comment by Koooooo-7** [comment]
Hi @flaneur7508  currently, it misses the `gauge` handy Options function. But you can use the custom config instead.
```go
	gauge := charts.NewGauge()

	setMinMax := charts.WithSeriesOpts(func(s *charts.SingleSeries) {
		s.Min = 1
		s.Max = 12
	})

	gauge.AddSeries("Foo", []opts.GaugeData{{Name: "Foo", Value: rand.Intn(50)}}, setMinMax)
	return gaug
```

**Comment by flaneur7508** [comment]
Thank you so much. That works fine.
