### ISSUE TITLE
Adding JSFuncStr destroys the chart

### ISSUE THREAD

**Issue by tobigiwa** [go-echarts/go-echarts#439]
### Describe your question

I tried using;
```go
...
	)
	bar.AddJSFuncStrs(opts.FuncOpts(aaa))
	bar.SetXAxis(data.XAxis).
		AddSeries("Daily uptime", generateBarItems(data.YAxis, data.XAxis)).SetSeriesOptions()
	return renderToHtml(bar)
}

var aaa = `
function(){
    const myChart = %MY_ECHARTS%;
    var dataLen = myChart.getOption().legend.data;
    console.log(dataLen);
}
````
It destroys the chart, looking into the browser, this is it effect
![Screenshot from 2024-06-01 08-08-47](https://github.com/go-echarts/go-echarts/assets/73890077/c5394b5b-7a63-434c-99c6-0ef41e6f2923)

Also I should add that, this is my own rendering template;
```go
const baseTpl = `
<div class="container">
    <div class="item" id="{{ .ChartID }}" style="height:30rem;"></div>
</div>
{{- range .JSAssets.Values }}
   <script src="{{ . }}"></script>
{{- end }}
<script type="text/javascript">
    "use strict";
    let goecharts_{{ .ChartID | safeJS }} = echarts.init(document.getElementById('{{ .ChartID | safeJS }}'), "{{ .Theme }}");
    let option_{{ .ChartID | safeJS }} = {{ .JSON }};
    goecharts_{{ .ChartID | safeJS }}.setOption(option_{{ .ChartID | safeJS }});
    {{- range .JSFunctions.Fns }}
    {{ . | safeJS }}
    {{- end }}

	window.addEventListener('resize', function() {
		goecharts_{{ .ChartID | safeJS }}.resize();
	});

	goecharts_{{ .ChartID | safeJS }}.setOption(%s);
</script>`

var tplOne string = fmt.Sprintf(baseTpl, firstOption)

func (r *chartRenderer) Render(w io.Writer) error {
	const tplName = "chart"
	for _, fn := range r.before {
		fn()
	}

	tpl := template.
		Must(template.New(tplName).
			Funcs(template.FuncMap{
				"safeJS": func(s interface{}) template.JS {
					return template.JS(fmt.Sprint(s))
				},
			}).
			Parse(tplOne),
		)

	err := tpl.ExecuteTemplate(w, tplName, r.c)
	return err
}
```
Also, @Koooooo-7 , it an earlier issue #434, reply https://github.com/go-echarts/go-echarts/issues/434#issuecomment-2134718967 you mentioned, i could rename my echart instance, i tried that but it always this error "variable name already use" even for name like "yyyyyyyyyy"... hence why I defaulted back  to the templating.

**You might  wonder why I console.log-ing the "legend.data", I want to add an action on each bar of the chart to fire a request with a query param, I could'nt find any other hack-ey way to add the data to the chart.**

### go-echarts version

v2.4.0-rc2

**Comment by Koooooo-7** [comment]
Hi @tobigiwa  I suppose you custom render is lack of the `injection` of echart instance.
Plz refer to the go-echarts renders implementations first before you do it, If you wanna implement yours with the go-echarts functionalities also.
https://github.com/go-echarts/go-echarts/blob/5b42df86f5049129367c8d0d84a11c49d5d56024/render/engine.go#L63

**Comment by tobigiwa** [comment]
already fixed this, thanks...closing it now.
