### ISSUE TITLE
[Bug] Colors for series in the legend do not match the colors set

### ISSUE THREAD

**Issue by dpajkovic** [go-echarts/go-echarts#443]
### Describe the issue

I have a line chart, and have added 4 different series. I want to have specific colors (1st and 3rd series same, 2nd and 4th same), but make 3rd and 4th series dashed.
I have used `opts.LineStyle` to set the color and the type of lines. The lines have correct colors, but in the legend it shows a different color for the series (picks it up from theme?). Funnily the legend correctly shows the 3rd and 4th series as dashed.

### How to reproduce this issue

```go
line:= charts.NewLine()
line.SetGlobalOptions(
	charts.WithInitializationOpts(opts.Initialization{
		Width: "1200px",
		Height: "600px",
	}),
	charts.WithTitleOpts(opts.Title{
		Title: "Number of events per week",
	}),
	charts.WithToolboxOpts(
		opts.Toolbox{
		Show: opts.Bool(true),
		Right: "10%",
		Feature: & opts.ToolBoxFeature{
		SaveAsImage: & opts.ToolBoxFeatureSaveAsImage{
		Type: "png",
		Title: "Download the graph as PNG",
		Show: opts.Bool(true),
	},
				},
			},
	),
	charts.WithLegendOpts(
		opts.Legend{
		Show: opts.Bool(true),
		// put legend at the bottom
		Bottom: "0",
	},
	),
)
line.SetXAxis(xDates).
	AddSeries("Number of production Events", yProdEvents, charts.WithLineStyleOpts(opts.LineStyle{
		// set line color to #516a91
		Color: "#516a91",
		Type: "solid",
	})).
	AddSeries("Number of pre-production Events", yPreProdEvents, charts.WithLineStyleOpts(opts.LineStyle{
		// set line color to #93b7e3
		Color: "#93b7e3",
		Type: "solid",
	})).
	AddSeries("Linear regression of production Events", calculateLR(yProdEvents), charts.WithLineStyleOpts(opts.LineStyle{
		// set line color to #516a91
		Color: "#516a91",
		Type: "dashed",
	})).
	AddSeries("Linear regression of pre-production Events", calculateLR(yPreProdEvents), charts.WithLineStyleOpts(opts.LineStyle{
		// set line color to #93b7e3
		Color: "#93b7e3",
		Type: "dashed",
	})).
	SetSeriesOptions(
		charts.WithLineChartOpts(
			opts.LineChart{
			Smooth: opts.Bool(true),
			Symbol: "none",
		},
		),
	)
f, err := os.Create("line.html")
```

### go-echarts version

v2.4.0-rc2

**Comment by Koooooo-7** [comment]
Hi @dpajkovic , the legend and the data is not in the same system, there is no corresponding legend for each data.
It needs set it individual and bind to the series via `name`.
Base on the code you provide:
```go
	legends := []map[string]interface{}{
		{
			"name": "Number of production Events",
			"itemStyle": map[string]string{
				"color": "#516a91",
			},
		},
		{
			"name": "Number of pre-production Events",
			"itemStyle": map[string]string{
				"color": "#93b7e3",
			},
		},
		{
			"name": "Linear regression of production Events",
			"itemStyle": map[string]string{
				"color": "#516a91",
			},
		},
		{
			"name":"Linear regression of pre-production Events",
			"itemStyle": map[string]string{
				"color": "#93b7e3",
			},
		}

		charts.WithLegendOpts(
			opts.Legend{
				...
				Data:   legends,
			},
		),
```

**Comment by dpajkovic** [comment]
Interesting. And a nice workaround. But I would argue that it stands to reason the line color should be picked up by the legend from the series setting the same way the type of the line is picked up. Thanks!

**Comment by Koooooo-7** [comment]
> Interesting. And a nice workaround. But I would argue that it stands to reason the line color should be picked up by the legend from the series setting the same way the type of the line is picked up. Thanks!

It is not a workaround, it is literally how it works in `echarts`. 
By default, the line and the legend both pick the Color from the global `Colors`.
When you custom the `line`'s color individually, it does not impact the global Colors which used by legend.
You can  config the global colors via `Colors`, but it doesn't means there has a steady corresponding legend color to the lines custom color, although you could set it as the same.
```go
line.Colors = []string{"#ae1029","#0065c2","#26c238", "#9876aa", "#fb8649",
		"#57904b","#d35b5c"}.

// line.Colors = []string{"#516a91","#0065c2","#93b7e3"},
```

**Comment by dpajkovic** [comment]
My argument is that legend picks up the line type (solid/dashed/dotted...), which I declare in `LineStyle` same as I do the color, and intuitively it should pick up the color as well. Is there a way to change the line type in legend `Data`?

Anyway, since it's the same in `echarts`, I can see this being an enhancement and not a bug.

**Comment by Koooooo-7** [comment]
> My argument is that legend picks up the line type (solid/dashed/dotted...), which I declare in `LineStyle` same as I do the color, and intuitively it should pick up the color as well. Is there a way to change the line type in legend `Data`?

The line style of `echarts` is another topic and its default behavior refer to its doc:
```
Legend line style. If its children have values as 'inherit', the values are inherited from corresponding series options.
```

I see the behavior between the `legend` and the `series` seems odd with some `inherit` and something not.
But it is what it is...

> Is there a way to change the line type in legend Data?


```go
{
			"name": "Number of production Events",
			"itemStyle": map[string]string{
				"color": "#516a91",
			},
                        // add the lineStyle
                        lineStyle: {
                              type: "dashed"
                         }
}
```
