### ISSUE TITLE
Overlaped charts

### ISSUE THREAD

**Issue by tandem97** [go-echarts/go-echarts#446]
Hi!
I was trying to create a single plot that displays line and kline. However, when I tried to combine the two graphs, the x-axis scale became distorted and no longer displayed the data correctly. The issue seems to be that the x-axis scales for the two individual graphs were not aligned properly when I tried to put them together. Or may be i did something wrong. Here is my code, thanks for help!

### Code pieces of your question

```go
package main

import (
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/components"
	"github.com/go-echarts/go-echarts/v2/opts"
)

func main() {
	page := components.NewPage()

	overlaped := klineBase()
	overlaped.Overlap(line())

	page.AddCharts(klineBase(), line(), overlaped)

	f, _ := os.Create("line.html")

	page.Render(f)
}

func line() *charts.Line {
	line := charts.NewLine()

	x := make([]int, 0, 3)
	y := make([]opts.LineData, 0, 3)

	for i := range 3 {
		x = append(x, i*2)
		y = append(y, opts.LineData{
			Value: i,
		})
	}

	line.SetXAxis(x).AddSeries("", y)

	return line
}

func klineBase() *charts.Kline {
	kline := charts.NewKLine()

	x := make([]int, 0, 5)
	y := make([]opts.KlineData, 0, 3)

	for i := range 5 {
		x = append(x, i)
		y = append(y, opts.KlineData{Value: []int{
			i, i + 1, i - 2, i + 2,
		}})
	}

	kline.SetXAxis(x).AddSeries("", y)

	return kline
}
```

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @tandem97 , the `X` axis is not a `number` axis, it is `Item`.  Based on your case, the line
```go
	for i := range 3 {
		x = append(x, i*2)
		y = append(y, opts.LineData{
			Value: i,
		})
	}

```
On single line charts, It has `'0', '1', '2'` as the items in X, the correspond value of y is 0,1,2 => ['0',0],['1',1],['2',2].
So is the Kline.
In the overlap, the Kline has the `5` **items** on X axis, but the line only 3 map values to the first 3 x items.
You need make new line items-value mapping suits the Kline's coor.

refer [xAxis.data](https://echarts.apache.org/en/option.html#xAxis.data)

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Hi! Thank you for answer. Yes in my case item count in kline and line is different. I cant just add new points, because my line data does not contains them. Overlap works correctly when all charts have the same item count, and there is no escape?

Yes, you can try to make the Kline same to `3` and check the overlap.
```go
	for i := range 3 {
		x = append(x, i)
		y = append(y, opts.KlineData{Value: []int{
			i, i + 1, i - 2, i + 2,
		}})
	}
```
--- 
If you wanna merge the line to the Kline with item=5, you can create a new Line for overlap instead of use the same Line directly.
```go
func lineOverlap() *charts.Line {
	line := charts.NewLine()

	x := make([]int, 0, 3)
	y := make([]opts.LineData, 0, 3)

	for i := range 3 {
		x = append(x, i*2)
		y = append(y, opts.LineData{
			// the xPos items index is double in Kline
                        // so, draw Line item on the index of 0,2,4 bases on the ordinal of the `axis.data` [0,1,2,3,4,5]`  of Kline.
			Value: []int{i * 2, i},
		})
	}

	line.SetXAxis(x).AddSeries("", y)

	return line
}

```

**Comment by tandem97** [comment]
@Koooooo-7 Yes, it works pretty well. Thank you for your answer!

**Comment by tandem97** [comment]
@Koooooo-7  Yes, it works pretty well. Thank you for your answer!
