### ISSUE TITLE
Possible to customize the size of the line Mark Points?

### ISSUE THREAD

**Issue by flaneur7508** [go-echarts/go-echarts#447]
### Describe your question

I'm enjoying using the line charts with mark points. Is it possible to customize the size of the markpoint because if the value displayed in the markpoint is any bigger than 9999 or thereabouts the display value is larger than the mark point itself.

### go-echarts version

v2.4.0-rc2

**Comment by Koooooo-7** [comment]
Hi @flaneur7508 , you could set the symbol size via :
```go
   line.SetXAxis(x).AddSeries("myLine", y).
		SetSeriesOptions(
			charts.WithMarkPointNameTypeItemOpts(
				opts.MarkPointNameTypeItem{Name: "Maximum", Type: "max"},
			),
			charts.WithMarkPointStyleOpts(
				opts.MarkPointStyle{
                                        // the size of the markLine symbol
					SymbolSize: 50,
				}),
		
```
