### ISSUE TITLE
Feature request: Graph Gravity Map

### ISSUE THREAD

**Issue by mikehawkes** [go-echarts/go-echarts#45]
Hi - Great library. Thank you.

Just wondering if there's any way to do a graph-based chart using this library? See the attached as an example.

![20191129 Commercial Overview - anon](https://user-images.githubusercontent.com/1488664/71351993-0a23c200-256d-11ea-989e-64bbb77022f4.png)

**Comment by chenjiandongx** [comment]
@mikehawkes 

Graph? https://github.com/go-echarts/examples/blob/master/examples/graph.go
