### ISSUE TITLE
[Bug] PageTitle does not work on liquid or gauge charts

### ISSUE THREAD

**Issue by flaneur7508** [go-echarts/go-echarts#457]
### Describe the issue

The page title remains the default even when the PageTitle is specified

### How to reproduce this issue

```
	liquid.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{
			Width:     badgeDefaultWidth,
			Height:    badgeDefaultHeight,
			PageTitle: "my_foo_title",
		}),
		charts.WithTitleOpts(opts.Title{
			Title:    title,
			Subtitle: "Compound growth (CMGR)",
			Link:     clickURL,
		}),
	)
```

### Other information

The above code results in HTML with the default title included.

### go-echarts version

v2.4.0

**Comment by Koooooo-7** [comment]
Hi @flaneur7508, they are different things.
Page title is the title of the HTML file. The chart title is its own chart name.

**Comment by flaneur7508** [comment]
I am referring to PageTitle

**Comment by Koooooo-7** [comment]
Hi @flaneur7508 , I can not reproduce it, it changes the PageTitle  correctly.
![pagetitle](https://github.com/go-echarts/go-echarts/assets/33706142/4ae0ff2d-830e-431a-8695-3ceff072cb89)

```go
	liquid := charts.NewLiquid()
	liquid.PageTitle = "liquid"
	liquid.SetGlobalOptions(
		charts.WithInitializationOpts(
			opts.Initialization{
				PageTitle: "my_foo_title",
			}),
		charts.WithTitleOpts(opts.Title{
			Title: "basic liquid example",
		}),
	)
```

**Comment by flaneur7508** [comment]
OK thanks for testing. If I copy your code above I still do not see a PageTitle (the default remains)

In my go.mod I have

	github.com/go-echarts/go-echarts/v2 v2.4.0

Below is my code:

```
liquid := charts.NewLiquid()
	liquid.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{
			PageTitle: "Go_Title",
			Width:     badgeDefaultWidth,
			Height:    badgeDefaultHeight,
		}),
		charts.WithTitleOpts(opts.Title{
			Title:    title,
			Subtitle: subTitle,
			Link:     clickURL,
		}),
	)
```

Are you testing on that version?

**Comment by Koooooo-7** [comment]
Hi @flaneur7508 , I suppose there may have some misunderstood.
What's the expectations of you about the page title?
It is not a `PageTitle` which displays on the Page, it is the HTML attr on the top tab.

**Comment by flaneur7508** [comment]
Yes. I'm looking to change the title in the browser tab from the default. 
<img width="283" alt="Capture d’écran 2024-07-02 à 09 13 02" src="https://github.com/go-echarts/go-echarts/assets/116429288/90765bcb-b29c-4e56-9d40-4904d9bc4633">

**Comment by Koooooo-7** [comment]
> Yes. I'm looking to change the title in the browser tab from the default. 

Strange.
BTW, do you wrapper the chars in a `Page` ?
```go
page := components.NewPage()
	page.AddCharts(
		barBasic(),
	)
```

**Comment by flaneur7508** [comment]
Good point. Thank you.
