### ISSUE TITLE
[Bug]cannot use true (untyped bool constant) as "github.com/go-echarts/go-echarts/v2/types".Bool value in struct literal

### ISSUE THREAD

**Issue by zzdboy** [go-echarts/go-echarts#458]
### Describe the issue

cannot use true (untyped bool constant) as "github.com/go-echarts/go-echarts/v2/types".Bool value in struct literal

### How to reproduce this issue

[Bug]cannot use true (untyped bool constant) as "github.com/go-echarts/go-echarts/v2/types".Bool value in struct literal

### go-echarts version

v2.4.0

**Comment by Koooooo-7** [comment]
Hi @zzdboy, IIUC, plz using the `opts.Bool(true)` instead since the bool in go-echarts is boxed to pointer with a nil val by default.
