### ISSUE TITLE
Area Chart

### ISSUE THREAD

**Issue by Mito91243** [go-echarts/go-echarts#460]
### Describe your proposal

Hello guys by any chance can you consider adding an area chart . It's available in charting libraries in NodeJS and it honestly looks pretty clean  .

### What the feature/improvement it should looks like?

![image](https://github.com/go-echarts/go-echarts/assets/85618190/f9fe07b6-bc5d-4290-a02e-ac8b01509505)

### Other information

I am still learning GO so I will not be able to implement is as I don't have the experience but just wanted to suggest the feature.

### Willing to implement it?

- [ ] Yes, I do

**Comment by Koooooo-7** [comment]
Hi @Mito91243 , go-echarts already support the `area` chart, see [lines example](https://go-echarts.github.io/go-echarts/#/en-us/charts/line).

**Comment by Mito91243** [comment]
ooh I didn't see that one my bad . Thank you !
