### ISSUE TITLE
[BUG] Kline candlestick default colors are inverted (red candles should be green and green ones should be red)

### ISSUE THREAD

**Issue by foobarchamp** [go-echarts/go-echarts#461]
### Describe the issue

**Describe the bug**
Kline candlestick colors are inverted (red candles should be green and green ones should be red)

**Expected behavior**
when candleitem.open < candleitem.close ==> candle should be green (showing red)
when candleitem.open > candleitem.close ==> candle should be red (showing green)

### How to reproduce this issue

**To Reproduce**
any candlestick chart. you can use code given below.

**Screenshots**
![image](https://github.com/goldmansachs/gs-quant/assets/15960033/2a3be5af-8e7f-4d5a-98c3-1e6e03133379)

**Systems setup:**
 - OS:Windows 11

**Additional context**
chart from kline base

code
```go

func klineBase() *charts.Kline {
	kline := charts.NewKLine()

	x := make([]string, 0)
	y := make([]opts.KlineData, 0)
	for i := 0; i < len(kd); i++ {
		x = append(x, kd[i].date)
		y = append(y, opts.KlineData{Value: kd[i].data})
	}

	kline.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Kline-example",
		}),
		charts.WithXAxisOpts(opts.XAxis{
			SplitNumber: 20,
		}),
		charts.WithYAxisOpts(opts.YAxis{
			Scale: opts.Bool(true),
		}),
		charts.WithDataZoomOpts(opts.DataZoom{
			Start:      60,
			End:        80,
			XAxisIndex: []int{0},
		}),
	)

	kline.SetXAxis(x).AddSeries("kline", y)
	return kline
}
```

### Other information

temp fix: setting correct colors manually
```go
kline.SetXAxis(x).AddSeries("kline", y, charts.WithItemStyleOpts(opts.ItemStyle{Color: "#00da3c", Color0: "#ec0000", BorderColor: "#008F28", BorderColor0: "#8A0000"}))
```

### go-echarts version

2.4.0

**Comment by neomantra** [comment]
This is not a bug but a [cultural preference](https://graphicdesign.stackexchange.com/questions/6982/except-china-which-country-will-use-red-for-up-and-green-for-down).  Other color combinations might be used for accessibility reasons as well.

I also think that without being specified specifically, `go-echarts` defaults to whatever upstream `echarts` defaults to. (I just checked that a bit in the tree.)

That said, it would improve the documentation to note the cultural and accessible issues and give examples to just like yours.

**Comment by Koooooo-7** [comment]
Hi @foobarchamp, as @neomantra  said.
It's the default behavior (maybe in someplace, it's totally opposite).
you need manually config it with your prefer.

**Comment by Koooooo-7** [comment]
Append solution.
```go
	kline.SetSeriesOptions(
		charts.WithItemStyleOpts(opts.ItemStyle{
			Color:        "#47b262",
			Color0:       "#eb5454",
			BorderColor:  "#47b262",
			BorderColor0: "#eb5454",
		}),
	)
```
