### ISSUE TITLE
[Question] Understanding wordclouds

### ISSUE THREAD

**Issue by flaneur7508** [go-echarts/go-echarts#463]
### Describe your question

How can I create a stable word cloud that displays the same five words each time I refresh the page? Currently, when I refresh the browser the wordcloud sometimes shows all the words, and other times it does not, even though the data remains unchanged. Here is an example of the word cloud I am working with below. This is the same wordcloud which is updated by refreshing the browser. I noticed this also happens in the example charts provided. 
The ranking of the word is determined by the value in the second column if the table in the screenshot.

### Code pieces of your question

<img width="1299" alt="Wc1" src="https://github.com/go-echarts/go-echarts/assets/116429288/3d6476c0-51db-4c9f-b694-51287d1a4adf">
<img width="1328" alt="Wc2" src="https://github.com/go-echarts/go-echarts/assets/116429288/d3982c21-a45c-4886-9ad3-bb54697c512f">

### go-echarts version

v2.4.0

**Comment by Koooooo-7** [comment]
Hi @flaneur7508 , unfortunately, the wordcloud calculates the words everytime in math random.
And it is the only behavior of the wordcloud.js ( which go-echarts depends) lib supports for now

**Comment by flaneur7508** [comment]
Ok thank you. That's unfortunate. If I have a WC with 5 words and only only 2 are displayed as per the first example above, I believe that should be considered a bug.

**Comment by Koooooo-7** [comment]
> Ok thank you. That's unfortunate. If I have a WC with 5 words and only only 2 are displayed as per the first example above, I believe that should be considered a bug. 

Absolutely. Maybe there may have workaround or options for this. I will investigate it  later when I'm go back home.
