### ISSUE TITLE
[Question] Radar tooltip

### ISSUE THREAD

**Issue by IceflowRE** [go-echarts/go-echarts#466]
### Describe your question

Currently the legend of the radar graph shows all values of the selected `RadarData`.
I would like to show the values of all series from the select indicator.
In my case all series have only one `RadarData` value.

---

Or is there an option to show the values of that indicator of all `RadarData` of one series if there would be more than one.

### Code pieces of your question

I would like to have
```
Agility
Giant: 50
Vampire: 80
Gnome: 40
```
if i hover over any Agility value.

```go
func exampleRadar() *charts.Radar {
	radar := charts.NewRadar()
	radar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Attributes",
			Right: "45%",
		}),
		charts.WithRadarComponentOpts(opts.RadarComponent{
			Indicator: []*opts.Indicator{{Name: "Agility", Max: 100}, {Name: "Strength", Max: 100}, {Name: "Speed", Max: 100}, {Name: "Damage", Max: 100}},
		}),
		charts.WithLegendOpts(opts.Legend{
			Left:   "left",
			Orient: "vertical",
		}),
	)
	radar.AddSeries("Giant", []opts.RadarData{{Name: "Giant", Value: []int{50, 90, 30, 70}}})
	radar.AddSeries("Vampire", []opts.RadarData{{Name: "Vampire", Value: []int{80, 60, 70, 40}}})
	radar.AddSeries("Gnome", []opts.RadarData{{Name: "Gnome", Value: []int{40, 20, 80, 20}}})

	return radar
}
```

### go-echarts version

v2.4.0

**Comment by Koooooo-7** [comment]
Hi @IceflowRE  Unfortunately, there is no a simple config to show the data per indicator/dimension.
