### ISSUE TITLE
[proposal] Can we support rendering images directly with e-chart without Rendering Engine

### ISSUE THREAD

**Issue by SangramBarge** [go-echarts/go-echarts#468]
### Describe your proposal

Can we add support for rendering images directly with e-chart without Rendering Engine. Currently it renders images in HTML and my use case is I do not want to be dependent on any rendering engine like Chromium or selenium. I want to directly render images without any headless browser. 

### What the feature/improvement it should looks like?

Should render images without the need to convert to HTML. Pure go e-chart library should support rendering out of the box. 

### Willing to implement it?

- [ ] Yes, I do

**Comment by Koooooo-7** [comment]
Hi @SangramBarge , I fully understand that it is not very convenient to use the extra stuff for the image render.
But AFAK, the underlying echarts relies on the JS/browser runtime to parse the configs to chart as a JS lib and it doesn't provide a generic image render solution.
Glad to see  there would have an individual solution for this without other 3rd-part supports.
