### ISSUE TITLE
AssetsHost doesn't work with local file path on Windows (at least)

### ISSUE THREAD

**Issue by matwachich** [go-echarts/go-echarts#471]
### Describe the issue

Setting AssetsHost to a custom local absolute path does not work.
The script src tag gets "#ZgotmplZ" instead of "folder_path/echarts.min.js"

### How to reproduce this issue

Set AssetsHost on some Chart or Page and Render.

### Other information

It seems that we should consider using template.URL for AssetsHost.

I solved this by using a relative path. So this bug concerns only absolute paths.

### go-echarts version

2.4.0

**Comment by Koooooo-7** [comment]
Hi  @matwachich , IIUC, you use the absolute path such as `src="/some/path/echarts.min.js"`.
When you open the file on browser, such as Chrome, it should visit on `localhost:port` as a server to retrieve the files via http.
Normally It should not work that adding a `local path` js asset to a html file, even though you use the `file://` protocol.
