### ISSUE TITLE
[Question] How to set a custom favicon?

### ISSUE THREAD

**Issue by nwtnsqrd** [go-echarts/go-echarts#475]
### Describe your question

I could not find any information in the examples or documentation about using a custom favicon for generated HTML pages. Is this possible to do, and if so, how?

### go-echarts version

v2.1.1

**Comment by Koooooo-7** [comment]
Hi @nwtnsqrd, Unfortunately, by default there's no a headers meta config.
You could customize the header tpl or using JS to modify it instead.
