### ISSUE TITLE
pie扇区颜色无法固定

### ISSUE THREAD

**Issue by ms8922** [go-echarts/go-echarts#48]
指定了颜色后 每次刷新  扇区的颜色都会随机变化  看了下源码是因为 range  map无序的原因导致的
建议Add方法增加一个数组key  来保证顺序 

func (c *Pie) Add(name string, data map[string]interface{},keys []string, options ...seriesOptser) *Pie {
	nvs := make([]datatypes.NameValueItem, 0)
	if keys==nil{
		keys= make([]string, 0)
		for k, _ := range data {
			keys = append(keys, k)
		}
	}
	for _, v := range keys {
		nvs = append(nvs, datatypes.NameValueItem{Name: v, Value: data[v]})
	}
	series := singleSeries{Name: name, Type: ChartType.Pie, Data: nvs}
	series.setSingleSeriesOpts(options...)
	c.Series = append(c.Series, series)
	c.setColor(options...)
	return c
}

**Comment by chenjiandongx** [comment]
嗯，确实会出现你描述的问题，但新增参数会看起来会破坏兼容性

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/97330431-3148cf80-18b3-11eb-965d-0c73feb28a7f.png)


v2 版本可以通过设置 Itemstyle 的 color 选项来设置颜色
