### ISSUE TITLE
[proposal] Support FilterMode option in opts.DataZoom struct

### ISSUE THREAD

**Issue by dexenrage** [go-echarts/go-echarts#480]
### Describe your proposal

Hi!
I need support for the filterMode option by your library in the opts.DataZoom structure. I attach the Apache ECharts documentation to this option for different types of dataZoom: [inside](https://echarts.apache.org/en/option.html#dataZoom-inside.filterMode) and [slider](https://echarts.apache.org/en/option.html#dataZoom-slider.filterMode).
Thank you.

### What the feature/improvement it should looks like?

The FilterMode option of the string type in the opts.DataZoom struct.

### Willing to implement it?

- [ ] Yes, I do

**Comment by Koooooo-7** [comment]
Hi @dexenrage  the FilterMode for data zoom is already done now. Plz upgrade to the latest version to access it.
