### ISSUE TITLE
How to render a line graph with Y-axis on the Right-Hand-Side?

### ISSUE THREAD

**Issue by Mozdoba** [go-echarts/go-echarts#481]
### Describe your question

Hello, does go-echarts support rendering Y-axis on the right-hand-side? 

Issue 204 linked below demonstrates how rendering a line graph with 2 Y-axis (on left & on right) at the same time, however can this be done simply with only a Y-axis on the right, and no Y-axis on the left?
https://github.com/go-echarts/go-echarts/issues/204

Simply specifying GridIndex: 1 does not do the trick, and results in errors.

### Code pieces of your question

l := charts.NewLine()

l.SetXAxis([]string{"1", "2", "3"})

l.WithYAxisOpts(
	opts.YAxis{
		Name:      "A",
		GridIndex: 1, 
		Type:      "value",
	},
)

l.AddSeries("A", []opts.LineData{{Value: 5, YAxisIndex: 1}, {Value: 3, YAxisIndex: 1}, {Value: 4, YAxisIndex: 1}}) 

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @Mozdoba , there has added on a new `Position` opt in y-axis now.
Plz upgrade to the latest version v2.4.2. You can set the position to `right` to make it.
```go
line.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "basic line example", Subtitle: "This is the subtitle."}),
		charts.WithYAxisOpts(opts.YAxis{Position: "right"}),
	)
```

**Comment by Mozdoba** [comment]
Thank you @Koooooo-7!
