### ISSUE TITLE
[Question] Proper way to do Formatters for XAxisLabel, DataZoom, Tooltip, etc...

### ISSUE THREAD

**Issue by Mozdoba** [go-echarts/go-echarts#484]
### Describe your question

Hi everyone,

I was recently using go-echarts v2.3.3, and before I upgraded to the latest version, I was able to use formatters like-so:
```
AxisLabel: &opts.AxisLabel{
	Show:      true,
	Formatter: opts.FuncOpts(`function(value) { return '$' + value.toLocaleString(); }`),
},
```

or
```
types.DataZoom(&opts.DataZoom{
   Type: "slider",
   LabelFormatter: opts.FuncOpts(`
        function (value, index) {
        var date = new Date(value);
        var texts = [(date.getMonth() + 1), date.getDate()];
        if (idx === 0) {
            texts.unshift(date.getYear());
        }
        return texts.join('/');
    }
`),
}),
```
 Now, after upgrading to 2.4.2 this no longer works.
 
 Is there a way to apply formatters to each option type? Or do I know have to use %MY_ECHARTS% as described here?
 https://go-echarts.github.io/go-echarts/#/en-us/dive-into?id=js-function-and-formatter-string

If so, how would I go about this?

Thank you

### go-echarts version

2.4.2

**Comment by Koooooo-7** [comment]
Hi @Mozdoba , I found there is a issue for the Formatter type that it hasn't been changed to `types.FunStr` yet.
So you need manually convert it to `string` for now, I will do the patch asap.
```go
AxisLabel: &opts.AxisLabel{Formatter: string(opts.FuncOpts(`function(value) { return '$' + value; }`))},
```

---

The `%MY_ECHARTS` is a placeholder for the echarts instance. you can inject it within your js to set the options.
I suppose this example may help you. It gets the echarts instance and set the `dataZoom` first item's filterMode to `node`.
 
```
lineChart := charts.NewLine()

const  JS_SET_FILTERMODE = `
    const instance = %MY_ECHARTS%;
    var option = instance.getOption();
    option.dataZoom[0].filterMode = 'none';
    instance.setOption(option);
`

lineChart.AddJSFuncStrs(JS_SET_FILTERMODE)
```
