### ISSUE TITLE
[Feedback] Using go-echarts as the Visualization Backend in a Data Analysis Project

### ISSUE THREAD

**Issue by TimLai666** [go-echarts/go-echarts#486]
Hi go-echarts team,

Thank you for creating such a powerful visualization tool. Recently, I developed a data analysis library called `Insyra`, which includes various data processing functions along with a plotting module. I’ve used `go-echarts` as the main visualization backend for Insyra, allowing us to easily integrate efficient and beautiful visualizations alongside data processing.

The goal of Insyra is to simplify the data handling workflow while seamlessly integrating `go-echarts` for charting capabilities. If you’re interested, feel free to check out the project—it could serve as a practical extension to `go-echarts`.

Thank you again for your contribution, which made it possible for me to build this project on top of it. I hope this project can help more users.

Best regards,
[HazelnutParadise/insyra](https://github.com/HazelnutParadise/insyra)

**Comment by Koooooo-7** [comment]
Hi @TimLai666 thx for your sharing and glad to see go-echarts can help you a lot.
Meanwhile, I will add the `Insyra` to `Ecosystem of go-echarts` section in our docs later.
Plz keep moving. 🚀

**Comment by TimLai666** [comment]
> Hi @TimLai666 thx for your sharing and glad to see go-echarts can help you a lot.
> 
> Meanwhile, I will add the `Insyra` to `Ecosystem of go-echarts` section in our docs later.
> 
> Plz keep moving. 🚀 
> 
> 

Wow! Thank u very much❤️. Hope u like it and I look forward to seeing Golang become mainstream for data analysis.

Let's work hard together.💪
