### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by chenjiandongx** [go-echarts/go-echarts#49]
Hi, guys

I'm @chenjiandongx , author of go-echarts. Cause of the busy working stuff, I already have no bandwidth to maintain this project. Thus I hope there is somebody to join the go-echarts dev-team to make it better.

If you are interested in it, please let me know or just contact me chenjiandongx@qq.com

**Comment by Koooooo-7** [comment]
/doge. :dog:

**Comment by pasdam** [comment]
🖐️

**Comment by KaiwenWang** [comment]
如果需要，我们这边可以参与项目的维护。同时我们也是使用方

**Comment by chenjiandongx** [comment]
> 如果需要，我们这边可以参与项目的维护。同时我们也是使用方

@KaiwenWang 欢迎贡献代码

**Comment by bygui86** [comment]
Hi guys, if there is the need of another maintainer, I could be interested :)

**Comment by chenjiandongx** [comment]
@bygui86 

Glad to see that news. Do you have a roadmap about go-echarts developments? You can list the features that you want to support in this issue.

**Comment by bygui86** [comment]
@chenjiandongx sorry for my late response, I thought to have some spare time to contribute to another open-source project (this one) but actually I was wrong.
I hope in the future to contribute here!
