### ISSUE TITLE
[Question] Animated Paths in Graph Chart 

### ISSUE THREAD

**Issue by Syndlex** [go-echarts/go-echarts#492]
### Describe your question

Is there a way to animate the Paths in the Graph Chart? It would be create to indicate a direction of flow. 

I look for somethink like this:
![Unbenanntes Diagramm-Seite-6](https://github.com/user-attachments/assets/cdc0ee3c-7de6-4e92-96cc-e4164e0ff1f7)

Edit: Ok i found it in echarts

It would be possible to set the LineStyle to Doted and set dashOffset: 
https://echarts.apache.org/en/option.html#series-graph.lineStyle.dashOffset

### go-echarts version

2.4.3

**Comment by Koooooo-7** [comment]
Hi @Syndlex thx for digging on this.
As per the options you mentioned, it seems that it wouldn‘t animate the line paths, there is a simple test on [echarts/Editor](https://echarts.apache.org/examples/en/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFU0DA4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4QxW07ThY0uU59NzAAO4TUzgrsLLNsDgGHjhdbZ1LsGmUTBDsTLixsJS07CMblAC6s-jHp-cOt0-iY0gAWQRmSw_Pb_HAAGXmi2Wh3QADMYGAev0CAAmSx7A7NHy0dJ7LLk4jQMZ-ABywAMODMTVR6FIBAAzNZfs08pzrJSiYdsqzYNTFHSGUzcSzWezYAAObmU9B82BcgmsoXNEWs8WSxnq2Wo-XmQYq2Bq0wCrU8imisU0qj0w1g42HU3mh1qqya1H8PYww4AemDsCw7gA1qlrkHmhHoNGyazdaj6DUHiYbBawG9ThQzHbiK0gVhsaDzJD8XHWZUFldU6y1ptttMLdrDgmzvlcCiHbANhADGBuARKxb0EwtAA3HDQFIxywAOlx7cFRcbzXTWiYBul7uaufY-edUuZRfQdeRhH78XWWwwO3bF_D7m7eV7N_7U_Ys_n9EXFc11tSlN1WDNd1PQ1TAPHIjxPF4XSZDk-BAlMLW3TMoP3F94JwAtKCQo111AjCIL3WAZVwvN8Ow2A3RI9CHUwyDELPGDqOPWi2NdVD_UDHkuy6HsTDA9B8kKAgACIDGAMBfAMKSLyMNYIjRNEEgLCweQDHJdNgL4UH4ABuIA), you could take a look.
For my understanding, echarts' animation is designed for the whole chart rendering, no specific animation option for the line paths between nodes in graph chart.

I suppose you could check the echarts options and have a try on the echarts Editor directly.
If you find any option works for your requirement but go-echarts misses it, please raising an issue and I will add it asap.

**Comment by Syndlex** [comment]
Hey, 

Writing as i investigate:

The Mozilla docs already talk about how to animate this:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineDashOffset#marching_ants

Tested it in the Editor: [Link](https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQ1AbrAAT6MC8jAjDQzM4XAFMYDADZtGSAXACS_IaNJ8AxjAHAB_ADScADHqq0AZgFdCSuPlSFlq9fwoBvaoxfNxLAKS69jANScaV0YlKyRUEQEEEVQyfHJqAF9aABIEYikAKQBlAHkAOVIAJRycgBUAfQAFAEFSgAk_RgByAHpcKDgoFqgkSTg2jq6IpABaYHxJGCgAI2GEACswwibtEzMLK0ZSYimABwhyRicXUEhYRAh8XAFsPCIyAxdUXY3rdmPXOFRwi12ALiOCU0zlcEXShFwAIA2iCgh8gi52p0ATsoPsEEoOgJiKgYPgBEgEMA0aQ1uZLNZSFBDvCES5VHBjDBrFAEIQoOpAnTGAl4nSkkEALrAoKTfFIaGw1y0oLs9QApqYAmMACyEyEM2GKylQTgIF2AgVqP22u5jBEUBAqGMcAVhCsAlN3KRUBRewgbNQ1yQIu5IiIAGsJYxjR7_YQg766ZjBDi8QS3WiPTHsbjxVGETAcMAAXAYMYBBmghbpgIRACZQiUBhc_nCzqEbtUEh8K8FXjiBA4E6zYZccS4IIYAqHNMEk0Gy4gZPzTMy5hLdbbUcZy5LtccnQhBb_ow8wWZ9OzUhMRFMPhxsvK0FxoQAToEAAWIsI4kADwBACZDy-XOGBFkeoRBWq7BOEuIKmETJKI6v6fPqhrNLgqCDgIuA9tyShMluhAEsGD4AMxwS46BXHAEAAgArMRjDtCgOSGIYfQAvgh4NgKriCiCCRcqc0DwMgUg5C8FKkM8rwGLylBAA)

I think it would need some CSS injection or so.
Any idea where i can find examples for this? 

I also Tried Keyframes but I can't get them to work and I can not find a Example with working Keyframe Lines.

I will also ask in the Issues of echart.

**Comment by Koooooo-7** [comment]
Hi @Syndlex , it is you do the best to figure it out. that's brilliant！
