### ISSUE TITLE
Have English documentation

### ISSUE THREAD

**Issue by marcelloh** [go-echarts/go-echarts#5]
I think, when you update your library to have English documentation, more people can use it :-)

**Comment by chenjiandongx** [comment]
yeap, I'm looking for someone can do this with me.

**Comment by yuankunzhang** [comment]
Hey guys, I just created a PR chenjiandongx/go-echarts#8 for the translation of README. This isn't enough but hopefully can provide a good starting point.

**Comment by knadoor** [comment]
Having a charts library written in Go is a great idea, Can you please ensure the project documentation and comms is done in English. I'm sure you'll get a lot more interest.

**Comment by yuankunzhang** [comment]
@knadoor I'm working on it.

**Comment by chenjiandongx** [comment]
English documentation is here -> [GoDoc](https://pkg.go.dev/github.com/go-echarts/go-echarts/v2)
