### ISSUE TITLE
[Question] User-provided / Custom Icons for Toolbox Features.

### ISSUE THREAD

**Issue by Mozdoba** [go-echarts/go-echarts#504]
### Describe your question

Is there a way to provide my own Icon for a Toolbox feature?

### Code pieces of your question

The options for each toolbox feature should expose an "Icon" property. The current implementation only offers "Show" and "Title"
![image](https://github.com/user-attachments/assets/c0bd26b9-d0fd-4039-9c20-bd619878e0a5)

`types.Toolbox(&opts.Toolbox{
							Show: opts.Bool(true),
							Orient: "horizontal",
							Top: "0%",
							Right: "3%", // same as grid.right
							Feature: &opts.ToolBoxFeature{
								DataZoom: &opts.ToolBoxFeatureDataZoom{
									Show: opts.Bool(true),
									Title: map[string]string{
										"zoom": "Zoom",
										"back": "Undo",
									},

								},
								Restore: &opts.ToolBoxFeatureRestore{
									Show:  opts.Bool(true),
									Title: "Reset",
								},
								SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
									Show: opts.Bool(true),
									Title: "Save",
								},
								UserDefined: map[string]opts.ToolBoxFeatureUserDefined{
									// must begin with "my" to avoid conflict with built-in features
									"myDownloadCSV": {
										Show:  opts.Bool(user.StripeSubscriptionActive),
										Title: "Download CSV",
										Icon: "M13.5 3H12H7C5.89543 3 5 3.89543 5 5V19C5 20.1046 5.89543 21 7 21H7.5M13.5 3L19 8.625M13.5 3V7.625C13.5 8.17728 13.9477 8.625 14.5 8.625H19M19 8.625V9.75V12V19C19 20.1046 18.1046 21 17 21H16.5M12 12V20M12 20L9.5 17.5M12 20L14.5 17.5",
										OnClick: echartTypes.FuncStr(opts.FuncOpts(charts_util.DownloadCSVFunction)),
									},
								},
							},
						}),`

### go-echarts version

v2.4.2

**Comment by Koooooo-7** [comment]
Hi @Mozdoba you need add the prefix `path://` in the vector string.

```
An image URL example:

'image://http://example.website/a/b.png' 

A dataURI example:

'image://data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7' 

Icons can be set to arbitrary vector path via 'path://' in ECharts. As compared with a raster image, vector paths prevent jagging and blurring when scaled, and have better control over changing colors.

For example:

'path://M30.9,53.2C16.8,53.2,5.3,41.7,5.3,27.6S16.8,2,30.9,2C45,2,56.4,13.5,56.4,27.6S45,53.2,30.9,53.2z M30.9,3.5C17.6,3.5,6.8,14.4,6.8,27.6c0,13.3,10.8,24.1,24.101,24.1C44.2,51.7,55,40.9,55,27.6C54.9,14.4,44.1,3.5,30.9,3.5z M36.9,35.8c0,0.601-0.4,1-0.9,1h-1.3c-0.5,0-0.9-0.399-0.9-1V19.5c0-0.6,0.4-1,0.9-1H36c0.5,0,0.9,0.4,0.9,1V35.8z M27.8,35.8 c0,0.601-0.4,1-0.9,1h-1.3c-0.5,0-0.9-0.399-0.9-1V19.5c0-0.6,0.4-1,0.9-1H27c0.5,0,0.9,0.4,0.9,1L27.8,35.8L27.8,35.8z'
```

**Comment by Mozdoba** [comment]
Thank you @Koooooo-7 , yes this is working for user-defined toolbox feature, however the "standard" features such as 'SaveAsImage' and 'Restore' don't have this option to my knowledge. I will have to update if I am mistaken.

**Comment by Mozdoba** [comment]
Thank you, your work on this project greatly appreciated!

**Comment by Koooooo-7** [comment]
Hi @Mozdoba , already add this icon option for builtin toolbox types, plz  upgrade to `v2.4.6` and have a try. :)

**Comment by Mozdoba** [comment]
Wow great! Thank you
