### ISSUE TITLE
无意冒犯，可是我越看越像百度的echarts

### ISSUE THREAD

**Issue by humSuperman** [go-echarts/go-echarts#53]
抱歉，无意冒犯。

**Comment by chenjiandongx** [comment]
前端实现就是百度的 Echarts，所以你这个描述有点问题。不是「像」，而是「是」🐶

**Comment by KISSMonX** [comment]
> There are many language bindings for Echarts, for example, pyecharts. go-echarts learns from pyecharts and has evolved a lot.

不看文档说明？

**Comment by chenjiandongx** [comment]
@KISSMonX 👍
