### ISSUE TITLE
github.com/go-echarts/go-echarts/templates/routers.html: no such file or directory

### ISSUE THREAD

**Issue by xing88** [go-echarts/go-echarts#57]
packr load templates error: stat  **GOPATH**/src/github.com/go-echarts/go-echarts/templates/routers.html: no such file or directory

**Comment by yuanqiuxing** [comment]
I also encourter such issue, which makes it hard to make an exe to spread.

**Comment by xiaowj** [comment]
1. `cd ${GOPATH}/src/github.com/go-echarts/go-echarts`
2. `chmod +x doPackr.sh`
3. `./doPackr.sh`
4. `cd your_project`
5. `go build`

have fun

**Comment by zx0721** [comment]
> 1. `cd ${GOPATH}/src/github.com/go-echarts/go-echarts`
> 2. `chmod +x doPackr.sh`
> 3. `./doPackr.sh`
> 4. `cd your_project`
> 5. `go build`
> 
> have fun

![image](https://user-images.githubusercontent.com/6317240/79355452-3fb34780-7f70-11ea-920d-cb44f9344e8f.png)

**Comment by xiaowj** [comment]
你要用doPackr.bat执行

**Comment by zx0721** [comment]
> @zx0721 你要用doPackr.bat执行

我就是用的bat但会报上面这个错误
