### ISSUE TITLE
x轴数据显示不全的问题， 求助

### ISSUE THREAD

**Issue by easyAation** [go-echarts/go-echarts#58]
x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？

**Comment by chenjiandongx** [comment]
可以把 X 轴的 Label 旋转

**Comment by Mutated1994** [comment]
> 可以把 X 轴的 Label 旋转

怎么旋转？没有找到对应代码

**Comment by Mutated1994** [comment]
> x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？



> x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？

兄弟直接改源码吧，挺简单的。

```Golang
func (c *Bar) validateOpts() {
	c.XAxisOptsList[0].Data = c.xAxisData
	c.XAxisOptsList[0].AxisLabel =AxisLabelOpts{Rotate: 20} // 20是旋转角度
        // ...
}

// github.com/go-echarts/go-echarts/charts/components.go
// XAxisOpts is the option set for X axis.
type XAxisOpts struct {
// ...
GridIndex int `json:"gridIndex,omitempty"`
// X 轴在 grid 区域中的分隔区域配置项
SplitArea SplitAreaOpts `json:"splitArea,omitempty"`
// X 轴在 grid 区域中的分隔线配置项
SplitLine SplitLineOpts `json:"splitLine,,omitempty"`

AxisLabel AxisLabelOpts `json:"axisLabel"` // 增加一个成员
}

type AxisLabelOpts struct {
	Interval int `json:"interval"`
	Rotate int `json:"rotate"`
}
```

**Comment by Mutated1994** [comment]
> 可以把 X 轴的 Label 旋转

把x轴的一些配置暴露出来呗

**Comment by easyAation** [comment]
> > 可以把 X 轴的 Label 旋转
> 
> 把x轴的一些配置暴露出来呗



> > x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？
> 
> > x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？
> 
> 兄弟直接改源码吧，挺简单的。
> 
> ```go
> func (c *Bar) validateOpts() {
> 	c.XAxisOptsList[0].Data = c.xAxisData
> 	c.XAxisOptsList[0].AxisLabel =AxisLabelOpts{Rotate: 20} // 20是旋转角度
>         // ...
> }
> 
> // github.com/go-echarts/go-echarts/charts/components.go
> // XAxisOpts is the option set for X axis.
> type XAxisOpts struct {
> // ...
> GridIndex int `json:"gridIndex,omitempty"`
> // X 轴在 grid 区域中的分隔区域配置项
> SplitArea SplitAreaOpts `json:"splitArea,omitempty"`
> // X 轴在 grid 区域中的分隔线配置项
> SplitLine SplitLineOpts `json:"splitLine,,omitempty"`
> 
> AxisLabel AxisLabelOpts `json:"axisLabel"` // 增加一个成员
> }
> 
> type AxisLabelOpts struct {
> 	Interval int `json:"interval"`
> 	Rotate int `json:"rotate"`
> }
> ```

非常感谢！

**Comment by Mutated1994** [comment]
> > > 可以把 X 轴的 Label 旋转
> > 
> > 
> > 把x轴的一些配置暴露出来呗
> 
> > > x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？
> > 
> > 
> > > x轴数据较多的话会有数据显示不全， 我没有在文档中找到相应的解决办法= = ， 请问有什么方法可以让它显示全吗？
> > 
> > 
> > 兄弟直接改源码吧，挺简单的。
> > ```go
> > func (c *Bar) validateOpts() {
> > 	c.XAxisOptsList[0].Data = c.xAxisData
> > 	c.XAxisOptsList[0].AxisLabel =AxisLabelOpts{Rotate: 20} // 20是旋转角度
> >         // ...
> > }
> > 
> > // github.com/go-echarts/go-echarts/charts/components.go
> > // XAxisOpts is the option set for X axis.
> > type XAxisOpts struct {
> > // ...
> > GridIndex int `json:"gridIndex,omitempty"`
> > // X 轴在 grid 区域中的分隔区域配置项
> > SplitArea SplitAreaOpts `json:"splitArea,omitempty"`
> > // X 轴在 grid 区域中的分隔线配置项
> > SplitLine SplitLineOpts `json:"splitLine,,omitempty"`
> > 
> > AxisLabel AxisLabelOpts `json:"axisLabel"` // 增加一个成员
> > }
> > 
> > type AxisLabelOpts struct {
> > 	Interval int `json:"interval"`
> > 	Rotate int `json:"rotate"`
> > }
> > ```
> 
> 非常感谢！

很开心可以帮助到你，那关闭issue吧。

**Comment by yokiy0828** [comment]
你这是怎么改的？改哪个文件？
