### ISSUE TITLE
charts: renderToWriter signature

### ISSUE THREAD

**Issue by sbinet** [go-echarts/go-echarts#59]
instead of:
```go
func renderToWriter(chart interface{}, renderName string, removeStr []string, w ...io.Writer) error {...}
```
https://github.com/go-echarts/go-echarts/blob/cbb3b43ade5d54354441b09f4bdbd0e6f74ebe67/charts/engine.go#L44

I believe it would be better written as:
```go
func renderToWriter(w io.Writer, chart interface{}, renderName string, removeStr []string) error
```

leaving users to call it with: `io.MultiWriter(w1, w2, w3)` if they want to.

**Comment by chenjiandongx** [comment]
@sbinet 

`io.MultiWriter`, It seems that I find something interesting never sees before. :) @xiaowj What do you think?

**Comment by xiaowj** [comment]
Processing

**Comment by chenjiandongx** [comment]
@sbinet After rethinking your advice, the `w ...io.Writer` signature looks ok for me because it is used commonly in the Golang world.

**Comment by sbinet** [comment]
Not in the Go stdlib (apart for io.MultiWriter) nor in the golang.org/x repos.

But ok.

**Comment by chenjiandongx** [comment]
@sbinet 

This project will be refactored totally soon. detailed info refer to #74 

 In the past year,  I have realized that the design of go-echarts is not elegant enough, including API/Struct naming, options configuration and render engine, etc...🐶.

Do you have other suggestions about this project?
