### ISSUE TITLE
TooltipOpts僅提供中文嗎？Are TooltipOpts only available in Chinese?

### ISSUE THREAD

**Issue by simar7** [go-echarts/go-echarts#66]
––––– English version below ––––

你好 ！

感謝您提供的精彩庫，到目前為止，我發現它非常有幫助。

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1254783/83315792-2dffc980-a1d7-11ea-9a3f-8e0f03557872.png">

的文字疊加層是否僅提供中文？ 是否可以將它們配置為使用瀏覽器語言或英語？

如果可以為我提供適當的代碼，我可以考慮向您發送拉取請求以添加該功能（如果該功能今天不存在）。

謝謝。

Hello!

Thank you for the wonderful library, so far I've found it very helpful.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1254783/83315792-2dffc980-a1d7-11ea-9a3f-8e0f03557872.png">

Are the text overlays for [`TooltipOpts`](https://github.com/go-echarts/go-echarts/blob/70059cac90d526579e010aa0e8005107f97ca68c/charts/components.go#L73) only available in Chinese? Is it possible to configure them to use the browser language or English? 

If you could point me to the appropriate code, I can look into sending you a pull request to add the feature if it doesn't exist today.

Thank you!

**Comment by Ringeltier** [comment]
Hello, I got the same problem but i fixed this with custom js.
Here is my code, hope I could help you.
~~~
RenameFn := fmt.Sprintf(`(function () {
		option_%s.toolbox.feature.saveAsImage = {title: 'Save statistic', lang:['Save as PNG']};
		option_%s.toolbox.feature.dataZoom = {title: {zoom:'Area zoom', back:'Area zoom restore'}};
		option_%s.toolbox.feature.dataView = {title: 'Data view', lang:['Data view','Close','Refresh']};
		option_%s.toolbox.feature.restore = {title: 'Refresh    '};
		myChart_%s.setOption(option_%s, true);
		document.getElementsByClassName('select')[0].style.visibility = 'hidden';
	})();`, line.ChartID, line.ChartID, line.ChartID, line.ChartID, line.ChartID, line.ChartID)
~~~

**Comment by simar7** [comment]
Thanks @Ringeltier that's very helpful!

**Comment by chenjiandongx** [comment]
This feature will be supported at the next version [v2](https://github.com/go-echarts/go-echarts/tree/v2)

**Comment by chenjiandongx** [comment]
@simar7 Are you interested in v2? I'm looking for the maintainers of this project.

**Comment by simar7** [comment]
@chenjiandongx thank you for the offer but at the moment I don't have the bandwidth to undertake maintainer-ship of a new project. If things change in the future, I will let you know!

**Comment by chenjiandongx** [comment]
@simar7 ok, contributing is always welcome :)

**Comment by chenjiandongx** [comment]
v2 usage:

```golang
func barSetToolbox() *charts.Bar {
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Bar-with-toolbox-opts",
		}),
		charts.WithToolboxOpts(opts.Toolbox{
			Show:  true,
			Right: "20%",
			Feature: &opts.ToolBoxFeature{
				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
					Show:  true,
					Type:  "png",
					Title: "Anything you want",
				},
			}},
		),
	)
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	return bar
}
```

![image](https://user-images.githubusercontent.com/19553554/85917862-648d3a80-b890-11ea-9922-742b80ad7dce.png)

**Comment by chenjiandongx** [comment]
v2 have been released :)

**Comment by thenick775** [comment]
Does this also affect the inner labels? I couldn't find a way to get these labels inside translated to english
<img width="905" alt="Screen Shot 2020-10-27 at 3 40 24 PM" src="https://user-images.githubusercontent.com/40526638/97369762-c5db0f80-186a-11eb-9001-24e393657419.png">

**Comment by chenjiandongx** [comment]
of cause YES!

```golang
func barSetToolbox() *charts.Bar {
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title: "Bar-with-toolbox-opts",
		}),
		charts.WithToolboxOpts(opts.Toolbox{
			Show:  true,
			Right: "20%",
			Feature: &opts.ToolBoxFeature{
				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
					Show:  true,
					Type:  "png",
					Title: "Anything you want",
				},
				DataView: &opts.ToolBoxFeatureDataView{
					Show:  true,
					Title: "dataview",
					Lang: []string{"data view", "turn off", "refresh"},
				},
			}},
		),
	)
	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	return bar
}
```

![image](https://user-images.githubusercontent.com/19553554/97382123-9af1c980-1905-11eb-9c24-7aab4a251d5f.png)

**Comment by thenick775** [comment]
Interesting, is there something wrong with my code here?
i keep getting `unknown field 'Lang' in struct literal of type opts.ToolBoxFeatureDataView`

```
charts.WithToolboxOpts(opts.Toolbox{
			Show:   true,
			Orient: "horizontal",
			Left:   "17%",
			Feature: &opts.ToolBoxFeature{
				nil,
				nil,
				&opts.ToolBoxFeatureDataView{
					Show:  true,
					Title: "View Data",
					Lang: []string{"Data View","Exit"},
				},
				nil,
			},
		}),
```
