### ISSUE TITLE
possible to add a release number?

### ISSUE THREAD

**Issue by nj-apps** [go-echarts/go-echarts#75]
Hello,
When I try  to build my project with gitlab CICD pipeline I get a checksum mismatch securty error. 

It seems this problem is recurent for go modules without any release number when using repository managers like artifactory. 
Could you please add a release number on master branch (ie v1.0.0) ?
Thanks a lot

**Comment by chenjiandongx** [comment]
@nj-apps 

I have added v1.0.0.0 for go-echarts. https://github.com/go-echarts/go-echarts/releases

You can try again now.

**Comment by nj-apps** [comment]
Thank you very much for your quick answer. 
The project builds on my computer when I use our artifactory proxy so It seems to be OK.
The CICD pipeline is not yet OK but it must be due to a cache. I will check tomorrow.
Thanks for your job! this is a very nice and useful library

**Comment by nj-apps** [comment]
CICD pipelines are working. Thanks a lot
