### ISSUE TITLE
Multiseries Chart - Disable series per default

### ISSUE THREAD

**Issue by Ringeltier** [go-echarts/go-echarts#77]
Is it possible to disable some series per default?
So that the behaviour will something like this on page call:
![image](https://user-images.githubusercontent.com/11855835/85414975-12d17100-b56d-11ea-8b4e-bfe02af4804a.png)

**Comment by chenjiandongx** [comment]
Echarts doesn't support this feature currently, hence...

**Comment by Ringeltier** [comment]
Hmm okay. Can you tell me which method you call on the click event to disable a series?
If so I can try to do it on my own.

**Comment by chenjiandongx** [comment]
I have looked up the Echarts docs, but nothing find. :)

**Comment by chenjiandongx** [comment]
@Ringeltier Do you want to join the go-echarts groups and maintain this project together?

**Comment by chenjiandongx** [comment]
@Ringeltier Do you want to join the go-echarts groups and maintain this project together?

**Comment by Ringeltier** [comment]
@chenjiandongx  I will think about it
