### ISSUE TITLE
How to incorporate this library into a pre-existing html/template ecosystem

### ISSUE THREAD

**Issue by sanddevil** [go-echarts/go-echarts#79]
Hey there - I would like to use your library on my website, but it is already using html/template and has an entire ecosystem built. I cannot see how I can integrate your library into my codebase easily. I believe you are using custom wrappers around text/template and your templates have HTML elements I don't want such as 

<!DOCTYPE html>
<html>
</html>

These are already defined in my own layouts. 

How can your templates be overridden so they will work in my page layout templates?  

Many thanks

**Comment by chenjiandongx** [comment]
At the new latest version v2, you can define your render logic and templates.
