### ISSUE TITLE
Bar chart doesn't render correctly for some reason

### ISSUE THREAD

**Issue by aakashbanerjee** [go-echarts/go-echarts#98]
```
`package main

import (
	"log"
	"os"

	"github.com/go-echarts/go-echarts/charts"
)

func main() {
	accounts := []string{"1111", "2222", "3333", "4444"}
	resacct := make(map[string]int64)
	resacct["1111"] = 25
	resacct["2222"] = 50
	resacct["3333"] = 10
	resacct["4444"] = 70
	bar := charts.NewBar()
	bar.SetGlobalOptions(charts.TitleOpts{Title: "Resource Counts by AWS Accounts"})
	for k, v := range resacct {
		bar.AddXAxis(accounts).AddYAxis(k, []int64{v})
	}
	f, err := os.Create("bar.html")
	if err != nil {
		log.Println(err)
	}
	bar.Render(f)
}
`
```
Output:

<img width="890" alt="Screen Shot 2020-09-17 at 6 54 55 PM" src="https://user-images.githubusercontent.com/601267/93546525-c8ffe900-f917-11ea-905e-4d30577823b4.png">

It is not very clear why all the bars are grouped by 1111 although the values are being displayed.

**Comment by Koooooo-7** [comment]
It is the case about the `group` stuff of echarts.
In ur code, that means 4 items' (`1111,2222,3333,4444`) values  in the first `1111`，the 4 bars belong to each item(`1111`,`2222`,`3333`,`4444`). lets adjust this case to make it  clear, I think if you run this two cases below, you will get it. 
```go
accounts := []string{"Mon", "Tues", "Wed", "Thur"}
	resacct := make(map[string]int64)
	resacct["Apple"] = 25
	resacct["Banana"] = 50
	resacct["Pear"] = 10
	resacct["Lemon"] = 70
	bar := charts.NewBar()
	bar.SetGlobalOptions(charts.TitleOpts{Title: "Fruits number in Monday"})
	for k, v := range resacct {
		bar.AddXAxis(accounts).AddYAxis(k, []int64{v})
	}
	f, err := os.Create("bar.html")
	if err != nil {
		log.Println(err)
	}
	bar.Render(f)
```

```go
accounts := []string{"Mon", "Tues", "Wed", "Thur"}
	resacct := make(map[string][]int64)
	resacct["Apple"] = []int64{25,30,40,50}
	resacct["Banana"] = []int64{50,30,10,50}
	resacct["Pear"] = []int64{10,30,25,50}
	resacct["Lemon"] = []int64{5,30,80,50}
	bar := charts.NewBar()
	bar.SetGlobalOptions(charts.TitleOpts{Title: "Fruits number in per day"})
	for k, v := range resacct {
		bar.AddXAxis(accounts).AddYAxis(k, v)
	}
	
	f, err := os.Create("bar.html")
	if err != nil {
		log.Println(err)
	}
	bar.Render(f)
```

BTW: Actually, the `bar.AddXAxis(accounts)` is unnecessary to add it so much times :).

**Comment by aakashbanerjee** [comment]
Thanks you @Koooooo-7 Your explanation solves the problem. However since I have more than 30+ fruits the output gets muddled like as shown in the screenshot. Is there a way to avoid this.
<img width="971" alt="Screen Shot 2020-09-24 at 8 45 03 PM" src="https://user-images.githubusercontent.com/601267/94224435-23b0bc00-fea7-11ea-947f-b29797888868.png">

**Comment by Koooooo-7** [comment]
It needs adjust the style of the legend. we r working on it also to provide more configurations.
There is a hacky one : 
Open the generated html, relapce the `legend` config in the configurations script, the legends should be on the right.
```js
 legend:{   
   orient:"horizontal",
    x:'right',
    y:' center',
    width:'100',
    padding:[10,30,0,0],
    itemWidth:30,
}
```
FYR, more  details of `legend` see the configurations docs [here](https://echarts.apache.org/en/option.html#legend).
and the current usage document of ours, [here](https://go-echarts.github.io/go-echarts/).

**Comment by aakashbanerjee** [comment]
Thank you for the workaround. I appreciate your help.
